### ISSUE TITLE
Conflict with api(S).php

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#100]
Just noticed that the WHMCS mod already has a file called api.php, so users using this mod have a conflict. 

original api.php: https://github.com/OpenGamePanel/OGP-Website/blob/master/api.php
mod: https://github.com/OpenGamePanel/OGP-WHMCS

**Comment by own3mall** [comment]
Thanks.  Should be fixed now.  Prepare for support threads.  All cronjobs will need to be redone that rely on the Steam Auto Update functionality.
