### ISSUE TITLE
Issues with update blacklist

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#104]
A while back I noticed that the blacklist entries piles up every time you add another one from the same 'folder', it will re-add everything ticked in this folder/page to the blacklist, when I talked about that with Adjo the other day I think he mentioned that having a small change in DB should fix that (like having a 'unique' attribute to the table or something like that), to avoid adding identical entries again and again. That does not break anything but you can end up having a really long list for only a few real items to blacklist.

Also I noticed that the blacklist does not work with the Extra modules I sometimes forget about that and lose my customizations to some extra modules when I update them (and when you are organized like me that often means you fucked up lol and need to remake your customization by hand). I looked in the code with my non coder eyes and it works completely different than the real OGP update when you update the extras so it may need lot of work there.. not top priority but that would be cool to have the blacklist working for everything.

**Comment by own3mall** [comment]
Should be all fixed in latest version.  Blacklist will be respected when updating extra modules.
