### ISSUE TITLE
game monitor Error

### ISSUE THREAD

**Issue by zarlo** [OpenGamePanel/OGP-Website#121]
when i try to go on to my game monitor i get "(My IP) is currently unable to handle this request."

**Comment by Zorrototo** [comment]
as I told you on forum (I guess it is you) post a screenshot of this because this is not an OGP error. please continue on this issue on the forum. http://www.opengamepanel.org/forum/viewthread.php?thread_id=5355&rowstart=20#post_26244

**Comment by Zorrototo** [comment]
Please manually apply this https://github.com/OpenGamePanel/OGP-Website/pull/122/commits/6135faa71c087821906ee8e239c12fd4b0af2702 and see if it fixes the issue.
