### ISSUE TITLE
Documentation - Prequesities for OGP agent has missing information.

### ISSUE THREAD

**Issue by szsahin** [OpenGamePanel/OGP-Website#133]
I am a CentOS user. And I read https://github.com/OpenGamePanel/OGP-Website/wiki for agent prequesities for CentOS 6. But get stuck after installing agent. Error code is an infamous one:
"Can't locate Path/Class/File.pm"
After some digging, I discovered that complete perl packages are these on CentOS 6.

perl-libwww-perl perl-ExtUtils-MakeMaker perl-XML-Parser perl-IO-Compress-Bzip2 **perl-Archive-Extract perl-Archive-Zip perl-Archive-Tar perl-Path-Class**

Please fix the documentation.

**Comment by own3mall** [comment]
Added to both CentOS 6 and CentOS 7 instructions.  Thanks.
