### ISSUE TITLE
Debian 7 installation guide mistakes

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#142]
I noticed tonight that curl package is missing from the installation note so it can not update Agent after installing it. Also on Debian 7 you have this error if you follow the installation notes:

Unable to locate package libarchive-extract-perl

I removed this package from the installation command line and went through the rest of the setup without any trouble.

edit: I found on old sourceforge wiki this:

```
 sudo apt-get install libxml-parser-perl libpath-class-perl perl-modules screen pure-ftpd rsync sudo e2fsprogs subversion unzip
 # The next package, the Perl module "Archive Extract", is already bundled  
 # under the package "perl-modules" in some distributions, for example on Debian 7.
 # If you see "E: Unable to locate package libarchive-extract-perl" it probably means
 # that you don't need to install it.
 sudo apt-get install libarchive-extract-perl
 # On some Debian based distributions you would need to install libarchive-zip-perl:
 sudo apt-get install libarchive-zip-perl
```

Maybe we may need to also add this kind of information in the website easy installers pages and github wiki

Also something I noticed is that by default sudo is not installed on Debian 8 and you have to install it manually, and on both 7 and 8 you need to add the user to the sudoers list to follow installation guide (which will then create the ogp_agent user with proper rights), so I think this is not clear for noobs.

Another thing, on Debian 7 it install ogp Panel in /var/www/html/ and setup tells you to go to http://localhost/index.php which leads to 404 error because apache root folder is at /var/www/ so you actually need to go to http://localhost/html/ maybe this can be more accurate by installing ogp in different folder, or by modifying the setup message accordingly depending on the OS.

**Comment by own3mall** [comment]
I'm pretty sure I tested it on Debian 8, and it worked fine.  Let's not support 7 anymore.

**Comment by Zorrototo** [comment]
sudo wasn't installed by default for me I don't know why.

**Comment by AlexanderCurl** [comment]
On Debian system sudo is not part to the base system, just Ubuntu craps installs it.

**Comment by own3mall** [comment]
I'll retest on my Debian 8 virtual machine at some point.

**Comment by own3mall** [comment]
Debian 7 instructions updated on the Wiki and on the OGP easy installers instructions at www.opengamepanel.org
