### ISSUE TITLE
Will this works on Servers on Windows server?

### ISSUE THREAD

**Issue by magnus505** [OpenGamePanel/OGP-Website#151]
Will this works on Servers on Windows server?

**Comment by Zorrototo** [comment]
There are builds of OGP made for Windows, find the Easy installers here http://www.opengamepanel.org/infusions/pro_download_panel/download.php?catid=9 (installing and configuring it all properly for you, you just have to correctly follow the instructions). Be sure to download the appropriate one (if 32bit or 64bit Operating System). Install Agent first (and File Zilla Server first if you want OGP to manage it), then Panel.

**Comment by magnus505** [comment]
can u help me install this? please

**Comment by magnus505** [comment]
https://antinggaming.us/contactus.php I'm on duty right now

**Comment by Zorrototo** [comment]
Please go to the forum for support.

**Comment by magnus505** [comment]
WEll I need help by setting it up
