### ISSUE TITLE
user_admin module .. module.php .. drop?!

### ISSUE THREAD

**Issue by TAPL-93** [OpenGamePanel/OGP-Website#152]
"DROP TABLE IF EXISTS" this just wipe out 200+ account just because the module uninstalled and then installed again.

Fix this!

**Comment by Zorrototo** [comment]
what? First read this in module page:

> The install/uninstall feature is not complete and might not work properly. WARNING: Data loss may occur in the OGP database!

Now for you knowledge, it's been more than a year that YOU CAN NOT UNINSTALL CORE MODULES so you are on an old version we do not support old version, if you were up to date obviously you couldn't do that... I hope for you that you had a database backup :\ But yeah, always be sure to have the Panel and Agent up to date this is critical to do that on everything you use, OGP included

**Comment by Zorrototo** [comment]
See here: https://www.dropbox.com/s/bbzs7585x71xxv4/Capture%20d%27%C3%A9cran%202017-06-10%2016.22.26.png?dl=0
And from when this is not possible to uninstall core modules; https://sourceforge.net/p/hldstart/svn/3367/ and it was on old sourceforge version..

**Comment by TAPL-93** [comment]
Yeah lucky i'm, i had 17 days old database backup and still had to recreate 51 accounts manually through phpmyadmin and have to create them with the same userid as before.

> always be sure to have the Panel and Agent up to date this is critical to do that on everything you use, OGP included

Let me show you what happened when i tried to update from 3391 to aede6b69353c501e1cbae931473e2ee0beed3c73

3391: https://prnt.sc/fi6osy
aede6b69353c501e1cbae931473e2ee0beed3c73: https://prnt.sc/fi6omn

Now you know why i'm still using old version. 😃

**Comment by FarukGamer** [comment]
@TAPL-93 do you have tried cleaning you browser cache after updating?

**Comment by Zorrototo** [comment]
Click REFRESH button in your web browser to get the new CSS files :awkward: :P

**Comment by FarukGamer** [comment]
What won't work always, press Crtl + F5 that forces a cache refresh

**Comment by TAPL-93** [comment]
Right, refresh button worked. 
@Zorrototo this was a testing VPS.
