### ISSUE TITLE
rcon presets not working

### ISSUE THREAD

**Issue by coolmodi** [OpenGamePanel/OGP-Website#16]
rcon presets are not wroking, tested for CS:GO. 

Edit: see reply for better fix

**Comment by coolmodi** [comment]
Ok, the problem is even easier, it doesn't check for command but for remote_send_rcon_command, so adding following into the preset form will fix it:

`echo '<input type="hidden" name="remote_send_rcon_command" value="">';`

**Comment by coolmodi** [comment]
Created a pull request for it as it seems good enough of a solution to me.

**Comment by own3mall** [comment]
Fixed with your changes.  Thanks for your contribution.
