### ISSUE TITLE
Options parameter of server_params doesn't work in the XML files

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/OGP-Website#19]
It is a very-very old issue. I already reported to DieFeM before and he said he will check it, but he is inactive...

In the xml files we have cli_params, reserve_ports, replace_texts, server_params and custom_fields where we can use **options=""** for first two and **<options></options>** for the rest to allow or disallow to use space and queries or nothing beetwen the server parameters and values.

The options work everywhere instead of server_params. Did it ever worked? Is it a bug or?
Here is an for example:
```
  <server_params>
   <param key="?ModID=" type="text" id="MODID">
      <default></default>
      <caption></caption>
      <options></options>
      <desc>Set Mods.</desc>
    </param>
  </server_params>
```

Then I have this in the server startup command line:
TheCenter?listen?Multihome=XXX.XXX.XXX.XXX?Port=XXXX?QueryPort=XXXX?MaxPlayers=XXX?ServerAdminPassword=XXXXXXXX ?ModID= "1234567" -server -log

So when I use nothing I have space and quotes for MoDID parameter. It doesn't matter what I set, it is always forced to use a space and quotes!

**Comment by own3mall** [comment]
So try it with a blank options element in your game server config XML:

`<options></options>`

The various possibilities are:

`if ($options == "tags")
				$file_content = preg_replace("/(<$default$var>)(.*)(<\/$default>)/m", '${1}'.$info_param.'${3}', $file_content, 1);
			elseif ($options == "tagValueByName")
				$file_content = preg_replace('/('.$default.'.*name="'.$var.'".*value=)(".*")/m', '${1}"' . str_replace('"', '\"', $info_param) . '"', $file_content, 1);
			elseif($options == "s")//separated
				$file_content = preg_replace("/$default/m", "$var $info_param", $file_content, 1);
			elseif ($options == "q")//quoted
				$file_content = preg_replace("/$default/m", "$var\"" . str_replace('"', '\"', $info_param) . "\"", $file_content, 1);
			elseif ($options == "sq")//separated & quoted
				$file_content = preg_replace("/$default/m", "$var \"" . str_replace('"','\"',$info_param) . "\"", $file_content, 1);
			elseif ($options == "sc")//separated & ending with a comma (used in JC2MP Example)
				$file_content = preg_replace("/$default/m", "$var $info_param,", $file_content, 1);
			elseif ($options == "sqc")//separated & quoted & ending with a comma
				$file_content = preg_replace("/$default/m", "$var \"" . str_replace('"', '\"', $info_param) . "\",", $file_content, 1);
			elseif ($options == "key-regex")//replace %key% in <var> and use a regular expression
			{
				$var = str_replace("%key%", $info_param, $var);
				$file_content = preg_replace("/$default/m", "$var", $file_content, 1);
			}
			else
				$file_content = preg_replace("/$default/m", "$var$info_param", $file_content, 1);`

Does that help?

**Comment by rocco27** [comment]
I used blank options element in my example and got space and quotas.
I knew all various possibilities except sc and sqc (reason never seen comma in xml before).
So I I use s, q or nothing I get sq in the end. Thats why I report.

**Comment by own3mall** [comment]
I will probably add a new option "n" to do what you want.  I'll work on it within the next few days.

**Comment by rocco27** [comment]
I tested all various, and it was alwaya same, space and quotas. I thonk this is buggy or maybe just missing this function?

**Comment by own3mall** [comment]
If that were true, Just Cause 2 MP server wouldn't work?  It uses sqc for parameters.  

See if that one works for you.  If it doesn't, maybe something has been messed up on your end.  Are you saying that no matter what option you pick, it ends up with a space and quoted?

**Comment by rocco27** [comment]
I checked Just Cause 2 MP xml and I see it uses sqc between <replace_texts></replace_texts>. This one works fine. I complained to server params only. This is the only one section where options never worked.

**Comment by own3mall** [comment]
Ah, ok... no need to get upset, I didn't understand.

Anyways, it looks like if you use "ns" it won't add a space or quotes?

`
<options>ns</options>
`

**Comment by rocco27** [comment]
Yo, this "ns" works, finally something. :)

**Comment by own3mall** [comment]
Yes, that's probably all you need there.
