### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by di57inct** [OpenGamePanel/OGP-Website#198]
I'm guessing this isn't the place to post this, but I need help.
I'm running CentOS 6.9 and when trying to restart proftpd service via your given commands in the tutorial
(sudo sed -i "s/^LoadModule\( \)*mod_auth_file.c/#LoadModule mod_auth_file.c/g" "/etc/proftpd.conf"
sudo service proftpd restart)
it gives me a fail notice
([root@80 ~]# sudo service proftpd restart
Shutting down proftpd:                                     [FAILED]
Starting proftpd:                                          [FAILED])

I tried reinstalling the service and then re-running the 2 given commands but it didn't work.
Would really appreciate some help. Thanks.

**Comment by own3mall** [comment]
Please post your issue in the forums.

http://opengamepanel.org

Additionally, please check the log files to retrieve why the service fails to start, and what you could do to fix it.
