### ISSUE TITLE
 the XML MOD KEY isn't updated in DB when changed

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#223]
As title says, when you change the mod key name in the XML file for a game server, then you click the UPDATE CONFIGS button, the mod key isn't updated in the database ogp_config_mods table, leading in an error in different Panel pages (for sur the Update with SteamCMD page for example, where it does not find the given mod key from database).

Ticking the box Reset Old Configs and clicking Update Configs button will fix it as it will wipe everything then re add each XML files with appropriate content.

But I think this is a bug, and it should maybe update the table ogp_config_mods when you just click Update Configs button.

As Rocco changed the mod keys in different XML files recently, users start to have problems regarding this http://www.opengamepanel.org/forum/viewthread.php?thread_id=4137&rowstart=140#post_29400

**Comment by rocco27** [comment]
Thanks for reporting. I wanted to do as well. Actually it is a very very old issue.

I think when the xml file or especially the "mod key" is updated, minimum we should be able to reconfigurate the it in bottom side of the Game Monitor/Edit page, but right now only the old one is exist. So it is not possible to reconfigurate, for example set the new one.

**Comment by Zorrototo** [comment]
Also as it is related (it is not an actual issue but more a question about the mod key), what is the rule we should follow for the mod key when a game has no mod, do we set the mod key as 'default' or do we use the game name or query protocol name?

Rocco likes to use 'default', and I prefer using the game name or protocol name.

For me the benefits of using the game name or protocol name, is that everything matches when you look in the DB, it makes things easier, readable and understandable, because if we change every mod key as default for the game with no mods to select, then the table ogp_config_mods will just be like that https://www.dropbox.com/s/rncz5751l09cyo8/Capture%20d%27%C3%A9cran%202017-10-20%2015.22.41.png?dl=0 but if we use the game name this table looks like that https://www.dropbox.com/s/32t1hga8s5da5kx/Capture%20d%27%C3%A9cran%202017-10-20%2015.22.02.png?dl=0

I'd like to have your opinion about this question, what you prefer, what makes more sense to you, and what we should follow as a rule when developing new XML files.

It doesn't change how it works in the end for OGP, as I said in another thread on forum I think it is just personal preference at this point.

**Comment by own3mall** [comment]
So if a mod is no longer available, you want OGP updated to use a different mod for server instances that were using an old one?  Why should it?  Now I have to program logic to decide what it should do?

I think if the mod no longer exists, it should be removed from the server completely.

**Comment by own3mall** [comment]
And await an admin change...

**Comment by Zorrototo** [comment]
Personally I don't want anything :D but the thing is that for example, there was this change recently https://github.com/OpenGamePanel/OGP-Website/commit/ecfdc7906ea150e6c2700f080eba942eb4097371#diff-11ac53f4e404bd8b83f7049035609a0aR22 (same thing in other XML files) the mod key has been renamed to 'default', this creates problems to user then when they go to the Update via Steam page it can not find the mod key from DB in the XML, because the mod key can not change when you click Update Configs.

The only way to fix it is to wipe all XML files from DB to regenerate the tables.

**Comment by rocco27** [comment]
If the mod key is not available anymore then OGP should remove and wait to set a new by admin or user. This could be the logic way.
Right now if there is no mod for the game server OGP always shows a popup messge to do that in Edit page. But if the mod key changed in the xml file, somehow nothing happens.

**Comment by own3mall** [comment]
Check it with the latest version.  Does it behave the way you imagined?

**Comment by rocco27** [comment]
It's perfect! Thank you!
