### ISSUE TITLE
Remote Server IP Joins Wrong

### ISSUE THREAD

**Issue by own3mall** [OpenGamePanel/OGP-Website#237]
@Adjokip and @Obada8 I could really use some help cleaning up the NATURAL JOINS against the remote_server_ips table.  I don't believe we want to be joining on this table?  I'm sure there are some instances where we do want to, but I think this is wrong and causing a lot of problems.

@Obada8 introduced all the page limit and count features, and that's when these problems started showing up.  We need to fix this.

See the changes here:

https://github.com/OpenGamePanel/OGP-Website/commit/290bc70d328719577cb91482b19db9a36f5f9ec4

We need to do more of that I think, but I'm not entirely sure.  @Obada8 , we need your help cleaning this up since you wrote the majority of this...

Attached is a screenshot of my game servers list before applying https://github.com/OpenGamePanel/OGP-Website/commit/290bc70d328719577cb91482b19db9a36f5f9ec4 :

![ogp_problem](https://user-images.githubusercontent.com/11792538/32145811-fddb7a0e-bc93-11e7-921d-9449736850b0.png)

With the fix:

![ogp_problem_fixed](https://user-images.githubusercontent.com/11792538/32145826-3ff8eb56-bc94-11e7-86f1-106ed54fd9f7.png)

**Comment by Adjokip** [comment]
This is something I happened to notice about a week ago and also mentioned in the following thread: http://www.opengamepanel.org/forum/viewthread.php?thread_id=5351&rowstart=20&showlast=true#post_29479

The join was only made to allow searching by IP - as indicated in the WHERE statement.

We could do what getHomesFor does, which also fixes it:

```sql
		$sql = 'SELECT %1$sserver_homes.*, %1$sremote_servers.*, %1$sconfig_homes.*, %1$shome_ip_ports.port
					FROM `%1$sserver_homes`
						NATURAL JOIN `%1$sconfig_homes`
						NATURAL JOIN `%1$sremote_servers`
						LEFT JOIN %1$shome_ip_ports 
							NATURAL JOIN %1$sremote_server_ips ON %1$sserver_homes.home_id=%1$shome_ip_ports.home_id ';
```

I quickly checked over the other search/limit features and they seem okay. Someone else or @Obada8 can verify.

The WHERE statement could also be cleaned up at the same time. Maybe something like this.

```php
public function getGameHomes_limit($page_gameHomes, $limit_gameHomes, $searchType, $searchString) {
	
	[...]

	if (!empty($searchType)) {
		if ($searchType == 'ip_port') {
			$sql .= "WHERE CONCAT_WS(':', %1\$sremote_server_ips.ip, %1\$shome_ip_ports.port) LIKE '%%$searchString%%'
						OR agent_ip = '$searchString'":
		}
		
		if ($searchType == 'ownedBy') {
			$sql .= "WHERE user_id_main IN (SELECT user_id FROM %1\$susers WHERE users_login LIKE '%%$searchString%%'
						OR user_id_main = '$searchString'";
		}
	}
```

**Comment by own3mall** [comment]
I'm fine with that.  We just need someone to fix it all, and I really don't want to do it haha.

**Comment by Adjokip** [comment]
I agree some of it is too complicated to follow along. I think it's mostly [getHomesFor_limit](https://github.com/OpenGamePanel/OGP-Website/blob/1b29dd7553dd5f44fdf4377a7f9fe55c5d2c1b85/includes/database_mysql.php#L1706) which is tedious to follow along due to the overuse of ternary operators and thus keep track of what should be happening.

#238 adds the join back with the code I displayed above. The other functions where the join was removed didn't seem to have the same issue... I removed the 'ip' field in the query build up as it was from the previously joined table.

**Comment by own3mall** [comment]
Excellent.  Thanks for your help!  The left join is a good solution, and allowing the user to specify how they want to search is how it should have been done in the first place.

**Comment by own3mall** [comment]
Your changes essentially take care of all of the issues mentioned, correct?  I'm just verifying because it looks like it does :+1: 

If so, I'll close out this issue.

**Comment by Adjokip** [comment]
Yes, any issue mentioned should've been taken care of.

The only thing I didn't look at were the *_limit search functions which build up the query string in one giant ternary operator :P

**Comment by own3mall** [comment]
In that case, I believe more work needs to be done.  Hopefully @Obada8 can apply the fixes you implemented for all of those functions and clean up the code when he gets a chance.

**Comment by own3mall** [comment]
Actually, I reviewed all places a join was performed on remote_server_ips, and I think it looks OK.  

I'll close this out.

**Comment by Obada8** [comment]
@own3mall I'm sorry for that bugs guys, i'm really busy with my work so i can't do anything these days.
@Adjokip Big thanks for your help.
