### ISSUE TITLE
EDIT SERVER COMMAND LINE

### ISSUE THREAD

**Issue by damian1231** [OpenGamePanel/OGP-Website#239]
Hi surely there must be some way to edit the command line on a CSS Server to add "-fps_max" and "-tickrate"

**Comment by andregomesdepaiva** [comment]
You can edit the game .xml or configurations in the panel to add any parameters you would like

**Comment by damian1231** [comment]
Please explain more detail where i add -tickrate 100 to the command line in this::

<game_config>
  <game_key>css_linux32</game_key>
  <protocol>lgsl</protocol>
  <lgsl_query_name>source</lgsl_query_name>
  <installer>steamcmd</installer>
  <game_name>Counter Strike Source</game_name>
  <server_exec_name>srcds_run</server_exec_name>
  <cli_template>%GAME_TYPE% %PID_FILE% %MAP% %IP% %PORT% %PLAYERS%</cli_template>
  <cli_params>
    <cli_param id="PID_FILE" cli_string="-pidfile ../" />
    <cli_param id="MAP" cli_string="+map" options="s" />
    <cli_param id="IP" cli_string="+ip" options="s" />
    <cli_param id="PORT" cli_string="-port" options="s" />
    <cli_param id="PLAYERS" cli_string="+maxplayers" options="s" />
    <cli_param id="GAME_TYPE" cli_string="-game" options="s" />
  </cli_params>
  <maps_location>cstrike/maps/</maps_location>
  <map_list>cstrike/maplist.txt</map_list>
  <max_user_amount>64</max_user_amount>
  <control_protocol>rcon2</control_protocol>
  <mods>
    <mod key="cstrike">
      <name>none</name>
      <installer_name>232330</installer_name>
      <installer_login>anonymous</installer_login>
    </mod>
  </mods>
  <replace_texts>
    <text key="control_password">
      <default>rcon_password.*</default>
      <var>rcon_password</var>
      <filepath>cstrike/cfg/server.cfg</filepath>
      <options>sq</options>
    </text>
    <text key="home_name">
      <default>hostname.*</default>
      <var>hostname</var>
      <filepath>cstrike/cfg/server.cfg</filepath>
      <options>sq</options>
    </text>
  </replace_texts>
  <server_params>
    <param key="-autoupdate -steam_dir {OGP_STEAM_CMD_DIR} -steamcmd_script {STEAMCMD_INSTALL_FILE}" type="checkbox_key_value">
      <caption>Auto-Update</caption>
      <desc>The server will automatically download official updates as they are released.</desc>
    </param>
    <param key="-insecure" type="checkbox_key_value">
      <caption>Disable Valve Anti-Cheat</caption>
      <desc>Will start the server without Valve Anti-Cheat technology.</desc>
    </param>
	<param key="-nohltv" type="checkbox_key_value">
      <caption>No SourceTV</caption>
      <desc>Disables SourceTV and closes its port.</desc>
    </param>
    <param key="-norestart" type="checkbox_key_value">
      <caption>No Restart</caption>
      <desc>Won't attempt to restart failed servers.</desc>
    </param>
    <param key="-nomaster" type="checkbox_key_value">
      <caption>Disable master server communication</caption>
    </param>
  </server_params>
  <custom_fields>
    <field key="sv_maxrate" type="text">
      <default>sv_maxrate.*</default>
      <default_value>0</default_value>
      <var>sv_maxrate</var>
      <filepath>cstrike/cfg/server.cfg</filepath>
      <options>s</options>
      <desc>Max bandwidth rate allowed on server ( bytes per second ), 0 == unlimited.</desc>
    </field>
	<field key="sv_minrate" type="text">
      <default>sv_minrate.*</default>
      <default_value>5000</default_value>
      <var>sv_minrate</var>
      <filepath>cstrike/cfg/server.cfg</filepath>
      <options>s</options>
      <desc>Min bandwidth rate allowed on server ( bytes per second ), 0 == unlimited.</desc>
    </field>
    <field key="sv_maxcmdrate" type="text">
      <default>sv_maxcmdrate.*</default>
      <default_value>66</default_value>
      <var>sv_maxcmdrate</var>
      <filepath>cstrike/cfg/server.cfg</filepath>
      <options>s</options>
      <desc>If sv_mincmdrate is > 0, this sets the maximum value for cl_cmdrate.</desc>
    </field>
    <field key="sv_mincmdrate" type="text">
      <default>sv_mincmdrate.*</default>
      <default_value>67</default_value>
      <var>sv_mincmdrate</var>
      <filepath>cstrike/cfg/server.cfg</filepath>
      <options>s</options>
      <desc>This sets the minimum value for cl_cmdrate. 0 == unlimited.</desc>
    </field>
    <field key="sv_maxupdaterate" type="text">
      <default>sv_maxupdaterate.*</default>
      <default_value>66</default_value>
      <var>sv_maxupdaterate</var>
      <filepath>cstrike/cfg/server.cfg</filepath>
      <options>s</options>
      <desc>Maximum updates per second that the server will allow.</desc>
    </field>
    <field key="sv_minupdaterate" type="text">
      <default>sv_minupdaterate.*</default>
      <default_value>67</default_value>
      <var>sv_minupdaterate</var>
      <filepath>cstrike/cfg/server.cfg</filepath>
      <options>s</options>
      <desc>Minimum updates per second that the server will allow.</desc>
    </field>
  </custom_fields>
  <list_players_command>status</list_players_command>
  <player_info_regex>#\#\s*(\d*)\s*\"(.*)\".*#</player_info_regex>
  <player_info>
    <index key="1">userid</index>
    <index key="2">Name</index>
  </player_info>
  <player_commands>
    <command key="Kick" type="hidden">
	  <string>kick "%Name%"</string>
	</command>
    <command key="Ban" type="select">
	  <option value="0">Permanent</option>
	  <option value="15">15m</option>
	  <option value="30">30m</option>
      <option value="60">1h</option>
	  <option value="1440">1D</option>
	  <option value="10080">1W</option>
	  <option value="43200">30D</option>
	  <string>banid %input% %userid% kick</string>
	</command>
	<command key="Change Nick" type="text">
	  <default>new nick</default>
	  <string>sm_rename #%userid% "%input%"</string>
	</command>
  </player_commands>
</game_config>

**Comment by damian1231** [comment]
<cli_param id="TICKRATE" cli_string="-tickrate" options="100" />

<cli_template>%GAME_TYPE% %PID_FILE% %MAP% %IP% %PORT% %PLAYERS% %TICKRATE%</cli_template>

Like this or?

**Comment by damian1231** [comment]
XML file 'modules/config_games/server_configs/counterstrike_source.xml' could not be validated with schema 'modules/config_games/schema_server_config.xml'. 
?:/

**Comment by damian1231** [comment]
omg all i want to do is edit the server command line wtf is this??? surely there is an easy way to just add it in ???

**Comment by Adjokip** [comment]
You don't need to edit that file.

Before starting the server, you should see a box above the start button titled "Extra Parameters" ... entering `-tickrate 100` before starting will set the tickrate to 100. [See here](https://i.imgur.com/sO9IIOF.png).

As for the validation error, it's because `options` can't be 100.

**Comment by own3mall** [comment]
If you can't see the extra parameters box, you'll need to fix the OGP permissions on that game server home using the panel.
