### ISSUE TITLE
Rsync installation occur error for local master server

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/OGP-Website#243]
When you have a Master Server (e.g. CoD4) and you want to update the sub-server, use Rsync Installation, it says master server available with details, countinue and you get "_unknow_rsync_mirror" error message.
If I do the same with another server where I have Steam Installation (e.g. Rust) I have Update from local master server, have same process and it works.
I tried different game type which has no Steam installation and had same error too.

I see @Adjokip changed Rsync Installation scripts 10 days ago with 2 commits, could it effect for this error?
[Fix Remote Command Execution ](https://github.com/OpenGamePanel/OGP-Website/commit/d974ff4044eb0deacd4bf5c3faa8bff8fefa54f2)
[Update rsync_install.php ](https://github.com/OpenGamePanel/OGP-Website/commit/597b887ff22e9e0e111c767b3b740786980c6561)

The string is also missing somehow from the OGP, I see why. Transifex sync removed.

**Comment by Adjokip** [comment]
What setting are you using for 'Available Rsync Servers' ? if it's local only and there's no local servers listed, that's the only way I've found it'll happen for me.

**Comment by rocco27** [comment]
All local and remote. Agent and Panel up-to-dated.

**Comment by Adjokip** [comment]
The only reason the message would appear is if `$url_id` is null or if the value doesn't exist in the `$rsync_sites` array.

Is there any mirrors listed? Does it happen if you don't update from the master server, but rather one of the rsync mirrors?

Maybe try and go to panel settings, disable auto refresh. After that, add `var_dump($_POST, $url_id, $rsync_sites);` after line 212 of `rsync_install.php` and try again to see what each of those variables contain.

This gist moves that check, maybe it'll fix it. https://gist.github.com/Adjokip/a963f75454cb246ab4fefb22e0f6ffe0

**Comment by rocco27** [comment]
Your gist helped. Local Master Server works now.

**Comment by rocco27** [comment]
One more thing, could you readd the missing string?

**Comment by Adjokip** [comment]
Sure. Added. :)
