### ISSUE TITLE
Owner Name in Addons

### ISSUE THREAD

**Issue by FIREFOXCYBER** [OpenGamePanel/OGP-Website#253]
Hey Guys,
I have a question , Is it possible to use owner name for addons , I mean something Like %OwnerName%
And if not exist i will be thankful if u add this replacement for addons of ogp .
Thanks.

**Comment by own3mall** [comment]
Explain.

**Comment by own3mall** [comment]
Actually, make your feature request in the forums:  https://opengamepanel.org/forum/viewforum.php?forum_id=4

Please explain your suggestion in depth in your forum post.
