### ISSUE TITLE
Critical bug on FTP.

### ISSUE THREAD

**Issue by TAPL-93** [OpenGamePanel/OGP-Website#254]
Changing the FTP username too quickly and repeatedly will result in creation of multiple FTP accounts.
https://prnt.sc/hbxk7i

Too long FTP username will result in bugged FTP accounts "Warning: invalid line".
https://prnt.sc/hbxksn

**Comment by own3mall** [comment]
1.  So don't do it too quickly?
2.  Define long.

**Comment by own3mall** [comment]
1.  Actually, this is not a bug.  This is a feature.  You can create multiple FTP accounts that share a directory.

**Comment by own3mall** [comment]
Also, what is your FTP setup?  Which method are you using?  There's like 5 different FTP modules that you can integrate with.

**Comment by own3mall** [comment]
Added length validation.

**Comment by TAPL-93** [comment]
I'm using pure-ftpd. I meant changing the FTP password from home editing, not ftp admin.

**Comment by own3mall** [comment]
I added validation in both places...
