### ISSUE TITLE
Creating new game server is not create home folder

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/OGP-Website#256]
Hi!

If I remember we had a discuss before about this. So I just reopen the case.

If we create a new game server, the home folder is missing. OGP creates only, if we use Steam, Rsync or Manual installation with a custom url. In these cases doesn't matter this issue, but it matters if we have the server file(s) on local pc and want to upload it via FTP client. Then we can not connect to the FTP server even if the account is created by OGP, because the home folder is missing, is not created yet!
So in this case we have to create the home folder in Game Monitor -> Edit  -> Browser in Home path -> Add folder - > Choose and set this folder. I'd say this is little stupied and maybe many user find the path on Windows or login to putty on Linux and use non-OGP user to create home folder and then they make a mess with owners/permissions/etc.

So my question is can we have create home folder function while a new game server created in OGP? It can help a lot if we have to upload the server files via FTP client which is quite normal process for old game servers.

**Comment by Zorrototo** [comment]
If it creates the folder automatically before real installation, it will create loads of empty folder after a while, because, personally, but I think I'm not the only one, I never use the default 'homeID number' folder assigned when creating server, I alway make one with another name to identify it better later.

If user can simply create folder then by clicking the button to confirm folder, in these rare games that do not use Rsync, Steam, or Manual (zip) installation, I think it is better the way it is currently.

Just my two cents but I prefer the way it is now than OGP creating folders every time you create a game server, as these game that require manual upload are a real minority. We always say to people on OGP forum that we're not here to tech them the basics, so if we now need to modify OGP to help them avoiding the creation of a folder, I'm speechless :D

**Comment by own3mall** [comment]
I'm very confused... on my test system, folders are automatically created when a game server is created, the home directory is changed, and when a FTP account is created...

**Comment by own3mall** [comment]
@rocco27 , try this changeset:

https://github.com/own3mall/OGP-Website/commit/e8966cc69a8362c2808ea344222c4dff009bd9dc

You can update to this version by putting own3mall in your Github Username field in the settings page to update to this version without doing any work.  

Is this what you were after?

**Comment by own3mall** [comment]
I believe creating the home should be done by the agent too no matter if FTP is enabled or not.  

Extra directories may be a problem, but it's not really... and the admin can cleanup anytime :)

**Comment by rocco27** [comment]
Well I am using proftpd with mod_sql.c module for i-MSCP and mod_auth_file.c module for OGP.
About the name of the home folder I always used the default, but of course maybe someone like to make it more personal, so an option to ask folder name could be fine for both side.

I go and check it @own3mall. Thanks.

**Comment by rocco27** [comment]
I updated the Panel with your commit. If I create a new game server, then the home folder is exist with default "home_id" name. For me it is fine now.
But for others who likes to customize home folder name, before install server files, maybe could be a perfect solution to have an extra option in the creating new server page, where we have to choose the Agent, the server type and the permissions. Set Home Path with the default value e.g. /user/ogpbot/OGP_User_Files/HOME_ID which can be changed. Then use Add game server will create the default or the custom home path. What do you thing guys?

Even if the

**Comment by own3mall** [comment]
It's not a bad idea, but if you change the path with this commit, that directory should also be created. 

I will add this ability :+1: for preset value in the panel  settings.

**Comment by own3mall** [comment]
Try my latest commits.  New setting in Panel Settings "Default game server home directory prefix" is what you can use.  Hover over the question mark for variables you can use.

**Comment by own3mall** [comment]
Fixed, and suggestion added.

**Comment by Zorrototo** [comment]
http://www.nooooooooooooooo.com/
