### ISSUE TITLE
Footer "Copied!" not translateable

### ISSUE THREAD

**Issue by fabm3n** [OpenGamePanel/OGP-Website#265]
Hey, I noticed that the "Copied" in the footer is not translatable.

![image](https://user-images.githubusercontent.com/11352551/33097197-9f0a7b5a-cf09-11e7-843a-5a292a6cf499.png)

**Comment by Zorrototo** [comment]
Because it is javascript message. Will need a dev to change it maybe to make it translatable.. but this is really not an issue as this would be rarely used, maybe by some OGP owners to then paste it in support forum but they need to speak english anyway so..

**Comment by fabm3n** [comment]
Sorry im used to post something like this to github. I will post it in the forums later.
