### ISSUE TITLE
More serious bugs found in the process of xml files

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/OGP-Website#284]
OGP Panel: first tried with 1710a207e659b79b42a72f4664a1ce42b8bf1cfb then 81a9eb06f939d731913826dd867f1c3081aed5e3
OGP Agent: e44a5b04912bf143f6da069d64520692d4ee63e3
OS: Debian 8 x64

OGP doesn't respect the order of the parameters in "cli_template".

Example from original CoD4 xml:
`  <cli_template>+set dedicated 2 %IP% %PORT% %BASE_PATH% %HOME_PATH% %SAVE_PATH% %FS_GAME% %PB% %EXEC% %CONTROL_PASSWORD% %PLAYERS% +map_rotate</cli_template>`

If we follow the "cli_template" , then we should have this (also it worked like this before):
+set dedicated 2 +set net_ip XXX.XXX.XXX.XXX +set net_port XXXXX +set fs_basepath /home/ogp_agent/OGP_User_Files/3 +set fs_homepath /home/ogp_agent/OGP_User_Files/3 +set fs_savepath /home/ogp_agent/OGP_User_Files/3 +set fs_game "mods/default" +set sv_punkbuster "0" +exec "server.cfg" +set rcon_password XXXXXXXXXXXXXXXX +set sv_maxclients 64 +map_rotate

But something is broken in the OGP and my actual startup command line with a CoD4 server is:
+set dedicated 2 +set net_ip XXX.XXX.XXX.XXX +set net_port XXXXX +set fs_basepath /home/ogp_agent/OGP_User_Files/3 +set fs_homepath /home/ogp_agent/OGP_User_Files/3 +set fs_savepath /home/ogp_agent/OGP_User_Files/3 +set rcon_password XXXXXXXXXXXXXXXX +set sv_maxclients 64 +map_rotate +set fs_game "mods/default" +set sv_punkbuster "0" +exec "server.cfg" +set sv_authorizemode 0

This "+set sv_authorizemode 0" is in my Extra Parameter, so it is correct in the end, but I see the "server_params" part moved from the fixed middle place to the end of the command line before the Extra Parameter part.

This kind of issue affects a lot to game server hosting!

**Comment by own3mall** [comment]
??????

I don't understand what you're trying to report.

This has always been the way it works?  Parameters are appended to the command line followed by extra parameters if there are any?

**Comment by rocco27** [comment]
In the xml file the parameters and variable have a fixed order. When I start the server the order is different.

+map_rotate should close the command (in my case there is an extra command because the extra parameter) but when I start the server it is in the kiddle...it was not like this before.

**Comment by rocco27** [comment]
I mean the start up command line is not same exactly ehat we have in the cli_template. It should follow, in this example all variables have a fixed position in the command line, but in the pratice the sequence is different.

**Comment by rocco27** [comment]
It was not like this before, I am sure.

**Comment by rocco27** [comment]
Edited my posts. I hope it is more clear now what is that. :)

**Comment by rocco27** [comment]
I just figured out my ARK test servers also have more problems and probably all type of game servers are effected by this issue where the sequences of the parameters are matter in statup command line.
This is because the parameters from "server_param" inserted to the wrong place.

**Comment by rocco27** [comment]
I also found another serius bug with "server_params", the Panel doesn't manage <options></options> anymore. I have this in the ark xml:

```
    <param key="?RCONEnabled=" type="select" id="RCON">
      <option value="True">True</option>
      <option value="False">False</option>
      <options>ns</options>
      <desc>Enable or disable remote control.</desc>
  </param>

and I have ?RCONEnabled= "True" in the startup command line.
```

**Comment by Zorrototo** [comment]
I can confirm that too, for example in Killing Floor 2 XML https://github.com/OpenGamePanel/OGP-Website/blob/master/modules/config_games/server_configs/killingfloor2_linux64.xml#L31 if I put Hard Difficulty and Short Length the parameter appear to be: `?Difficulty= "0" ?GameLength= "0"` instead of `?Difficulty=0?GameLength=0` it adds quotes, but also space before and after the quotes.

**Comment by own3mall** [comment]
Please confirm if fixed in the latest version.

**Comment by Zorrototo** [comment]
works for me, wait for Rocco to confirm the other problem with order of CLI parameters.

**Comment by rocco27** [comment]
Both bugs eliminated. Thank you!
