### ISSUE TITLE
Multi Theft Auto Config Update

### ISSUE THREAD

**Issue by lamjed001** [OpenGamePanel/OGP-Website#288]
`<game_config>
  <game_key>multitheftauto_linux64</game_key>
  <protocol>lgsl</protocol>
  <lgsl_query_name>mta</lgsl_query_name>
  <game_name>Multi Theft Auto</game_name>
  <server_exec_name>mta-server64</server_exec_name>
  <console_log>mods/deathmatch/logs/server.log</console_log>
  <max_user_amount>4096</max_user_amount>
  <control_protocol>lcon</control_protocol>
  <mods>
    <mod key="default">
      <name>None</name>
    </mod>
  </mods>
  <replace_texts>
    <text key="home_name">
      <default>servername</default>
      <filepath>mods/deathmatch/mtaserver.conf</filepath>
      <options>tags</options>
    </text>
    <text key="ip">
      <default>serverip</default>
      <filepath>mods/deathmatch/mtaserver.conf</filepath>
      <options>tags</options>
    </text>
    <text key="port">
      <default>serverport</default>
      <filepath>mods/deathmatch/mtaserver.conf</filepath>
      <options>tags</options>
    </text>
    <text key="max_players">
      <default>maxplayers</default>
      <filepath>mods/deathmatch/mtaserver.conf</filepath>
      <options>tags</options>
    </text>
  </replace_texts>
  <custom_fields>
    <field key="HTTP Port" type="text">
      <default>httpport</default>
      <default_value>22005</default_value>
      <filepath>mods/deathmatch/mtaserver.conf</filepath>
      <options>tags</options>
      <access>admin</access>
      <desc>Port of the http server (it could be same as server port).</desc>
    </field>
    <field key="Owner Email" type="text">
      <default>owner_email_address</default>
      <default_value></default_value>
      <filepath>mods/deathmatch/mtaserver.conf</filepath>
      <options>tags</options>
      <desc>This parameter specifies the contact email addresses for the owner(s) of this server.</desc>
    </field>
    <field key="Voice" type="select">
      <default>voice</default>
      <option value="1">Enable</option>
      <option value="0">Disable</option>
      <default_value>0</default_value>
      <filepath>mods/deathmatch/mtaserver.conf</filepath>
      <options>tags</options>
      <desc>This parameter specifies whether or not to enable player voice chat in-game.</desc>
    </field>
  </custom_fields>
  <configuration_files>
    <file description="Server Configurations">mods/deathmatch/mtaserver.conf</file>
  </configuration_files>
</game_config>`

**Comment by lamjed001** [comment]
Add Custom Fields 
`    <field key="Owner Email" type="text">
      <default>owner_email_address</default>
      <default_value></default_value>
      <filepath>mods/deathmatch/mtaserver.conf</filepath>
      <options>tags</options>
      <desc>This parameter specifies the contact email addresses for the owner(s) of this server.</desc>
    </field>
    <field key="Voice" type="select">
      <default>voice</default>
      <option value="1">Enable</option>
      <option value="0">Disable</option>
      <default_value>0</default_value>
      <filepath>mods/deathmatch/mtaserver.conf</filepath>
      <options>tags</options>
      <desc>This parameter specifies whether or not to enable player voice chat in-game.</desc>
    </field>`
Add configuration file
`  <configuration_files>
    <file description="Server Configurations">mods/deathmatch/mtaserver.conf</file>
  </configuration_files>`

**Comment by rocco27** [comment]
Please more spam everywhere. I already warned you on the forum.
I will update mta xml, haven't forget...
