### ISSUE TITLE
can't get registration email from http://www.opengamepanel.org/

### ISSUE THREAD

**Issue by HTlocal** [OpenGamePanel/OGP-Website#31]
Hi,

maybe not the right place to post but I can't post on the discussion forum without any account, so I thought I'll try here.
Have sent 3 registrations (users: htlocal, httlocal, htlocal2), 2 of the mail addresses are hosted by me, the other one externally.
I just want the agent since a friend of mine already set up an open game panel server.

Cheers,
local

**Comment by own3mall** [comment]
Have you tried using a gmail account?

**Comment by HTlocal** [comment]
still don't have an account but got everything running now, so I'm good for now
