### ISSUE TITLE
Monitor button icons are not centered, and "Show Size" monitor button does not show size centered

### ISSUE THREAD

**Issue by Tank-Missile** [OpenGamePanel/OGP-Website#318]
![buttons](https://a.uguu.se/JaoHAZdXvQ2d.png)

**Comment by own3mall** [comment]
So, you'd like it centered vertically and horizontally?

**Comment by Tank-Missile** [comment]
Yes, for consistency sake.

**Comment by own3mall** [comment]
This would require HTML structure and CSS changes.  If you'd like to provide a working solution, feel free to open a pull request.  

This is a non-issue as everything is currently aligned to the top.  It may look like some of the buttons are centered, but that depends on how the icon is cropped.

**Comment by own3mall** [comment]
I did make a slight change so that the size text is centered vertically.  Again, it's impossible to have these buttons perfectly centered unless they are all cropped the same when they're saved.
