### ISSUE TITLE
Cannot add IPv6 address!

### ISSUE THREAD

**Issue by AlexanderCurl** [OpenGamePanel/OGP-Website#320]
When I trying to add IPv6 address to my panel, it just came up with random numbers on my agent.
Screenshots attached:

https://imgur.com/a/UGEIV

**Comment by own3mall** [comment]
ipv6 isn't supported... yet.

**Comment by own3mall** [comment]
Can you tell me exactly what screen (the module URLs) you were getting this?  I'm thinking about making OGP support IPv6.

**Comment by AlexanderCurl** [comment]
Yes, it happened in the Agent side, when you link the agent with the webpanel.

**Comment by rocco27** [comment]
Where do you use IPv6? CoD4? :)

**Comment by AlexanderCurl** [comment]
@rocco27 CoD4 doesn't require, because +set net_ip6 do the job just fine. I wanted to use to my TS3 server.

**Comment by AlexanderCurl** [comment]
@own3mall the pace is: /home.php?m=server
This site i wanted to add the agent ipv6 address as well.

**Comment by own3mall** [comment]
Closing for now... maybe we'll do this in the future.
