### ISSUE TITLE
Not all dependencies/extensions are checked before installation

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#329]
I don't have the full list, but I'm sure the install.php file does not check for all needed extension. For sure, it does not check for the php-zip extension required to update Panel. I guess we could maybe have this file to check everything the Panel uses, and then in install.php have checks for everything, and mark the required base Panel extension in green/red for installed/not found (not found blocking the install process) and for Extras modules which may require some extension we can maybe mark them as green/ORANGE for installed/not found (orange not blocking installation but giving a warning) this way the user can also install other extensions he may require if he installs one of the other modules which may require additional extension (out of my head I don't see any but it may be possible that some Extra module require a specific extension).

**Comment by own3mall** [comment]
Should be addressed by:

https://github.com/OpenGamePanel/OGP-Website/pull/337
