### ISSUE TITLE
rows inserted into ban_list table never removed.

### ISSUE THREAD

**Issue by TAPL-93** [OpenGamePanel/OGP-Website#335]
As the title, the rows inserted into ban_list table never removed, the table grow over time which result in thousands of unnecessary rows.

**Comment by Zorrototo** [comment]
thousands? you really have that much users? or you really have that much people trying to bruteforce Panel credentials?

Anyway the fact this table never empties is a good way to see the amount of people trying to break in if it is not legit password mistakes. Does it create a problem if this table grows over time? What do you suggest?

**Comment by TAPL-93** [comment]
i have hosted over one thousand game servers in the last two years, so yeah i do have that much of users. Also those users have dynamic IP address and ogp do insert the IP in the table even if that was a successful login.

> Does it create a problem if this table grows over time?

Well, it's unnecessary rows that grow up over time with no limit (infinity), things should be as efficient and optimized as possible.

> What do you suggest?

1- Successful logins should not be inserted in the table.
2- Any rows that have the value of logging_attempts as "0" should be removed from the table.

**Comment by own3mall** [comment]
Should be addressed by:

https://github.com/OpenGamePanel/OGP-Website/pull/337
