### ISSUE TITLE
Wiki is missing the WINE installation procedure, and WHMCS mod

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#34]
As title says, GitHub wiki is missing the WINE information provided here https://sourceforge.net/p/hldstart/wiki/Installation%20Notes/#running-windows-based-game-servers-on-linuxtm-using-wine

I guess it would be better if everything was imported here.

It is also missing the WHMCS mod. https://sourceforge.net/projects/ogpextras/files/Mods/

**Comment by own3mall** [comment]
WINE Guide:  https://github.com/OpenGamePanel/OGP-Website/wiki/Running-Windows-Game-Servers-on-Linux-using-WINE

WHMCS mod:  https://github.com/OpenGamePanel/OGP-WHMCS

Thanks for pointing that out.
