### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by fodw1** [OpenGamePanel/OGP-Website#340]
I'm getting the following error in my linux agent after update

`Can't locate object method "sockhostname" via package "▒▒]" (perhaps you forgot to load "▒▒]"?) at /usr/share/perl5/vendor_perl/HTTP/Daemon.pm line 64``

And through the website the agent appears as offline
![asdfw](https://user-images.githubusercontent.com/39199713/39939856-f13d1982-552d-11e8-81df-99af3e952dbc.jpg)

**Comment by own3mall** [comment]
Please post issues like this in the forums https://opengamepanel.org/forum/viewforum.php?forum_id=2.  
Give us as much information as possible so we can further assist you (include OS details - and did you search this already - https://www.google.com/search?client=firefox-b-1-ab&ei=weD1WunmIMzbjwSX_a74Cw&q=locate+object+method+sockhostname+via+package&oq=locate+object+method+sockhostname+via+package&gs_l=psy-ab.3...74845.76539.0.76730.2.2.0.0.0.0.88.148.2.2.0....0...1.1.64.psy-ab..0.0.0....0.pU9wNziMFgw)

**Comment by AlexanderCurl** [comment]
I had the same issue yesterday, probably the Daemom.pm is too old, and it has a bug. Already opened a thread on the forum.

**Comment by AlexanderCurl** [comment]
And there is the solution as well.
