### ISSUE TITLE
Multiple IP addresses issue

### ISSUE THREAD

**Issue by AlexanderCurl** [OpenGamePanel/OGP-Website#341]
Hi.

I have a server with 2 ip addresses for purposes, and I wanted to add a server to my another IP address, but the panel seems to be buggy. I added the 2 ip addresses for the agent, but Im unable to select my secondary IP address to a game server.

Screenshots attached:
https://imgur.com/a/WCfhkEt

**Comment by rocco27** [comment]
Actually there is an other small issue when more IPs assigned to same Agent.

When you create a new game server, the Panel doesn't list all IPs, only the first one which was used while the Agent added to the Panel. If more IPs added to Agent, I think OGP should list all IPs.

[](https://i.imgur.com/jOF1pWN.png)

**Comment by own3mall** [comment]
This is fixed right?  @DieFeM took care of it?

https://github.com/OpenGamePanel/OGP-Website/commit/b020de5a7253c7671c6eb12753f133a8db9782fc

**Comment by DieFeM** [comment]
Yes, it is already fixed. Sorry I don't have the habit of closing issue threads. I'll click at "Close and comment" now.
