### ISSUE TITLE
[Question] About the OpenGamePanel API

### ISSUE THREAD

**Issue by OnlyHardOfficial** [OpenGamePanel/OGP-Website#349]
Hello everyone! I do not know if it would be better to talk here or through the forum! I am a user of this fantastic OpenSource softwer, with everything I have a few questions to try soon to develop a form of connection, namely an extension to a SaaS softwer.
For this reason I would like to know with what kind of API OpenGamePanel works and the existing documentation available to cover the possibilities between these two Softwers!
I would feel happy, do not get me wrong, but it will be a positive idea in all respects related to the subject hosting game servers

**Comment by own3mall** [comment]
Look at the WHMCS https://github.com/OpenGamePanel/OGP-WHMCS project for a sample API.  This would be better discussed in the forum, but hopefully the above information can help you.
