### ISSUE TITLE
Error after install : Login info invalid

### ISSUE THREAD

**Issue by Dovahkiin-Warrior** [OpenGamePanel/OGP-Website#354]
I recently uploaded the latest webscript to my new machine for hosting and I have the sql info right.

The SQL tables have the right password for my username, but on login it says "Invalid login information entered. Redirecting..." and takes me back to the login page. Why?

Server timezone is set properly, SQL is working properly, and my user and pass is alphanumeric (for example auf5jrm2) and it will not work.

**Comment by rocco27** [comment]
Windows or Linux?

**Comment by own3mall** [comment]
Your PHP sessions aren't working.  Troubleshoot that.  Post in forums for support.  No one else has this issue.
