### ISSUE TITLE
White box when trying to exchange permissions

### ISSUE THREAD

**Issue by fodw1** [OpenGamePanel/OGP-Website#384]
Hello, I tried to change the permissions of my server as administrator and nothing appearing.

[screenshot1](https://hostfreeimg.com/image.php?di=Y2YS)
[screenshot2](https://hostfreeimg.com/image.php?di=OR04)
[screenshot3](https://hostfreeimg.com/image.php?di=UH20)

page: home.php?m=user_games&p=assign&user_id=1

**Comment by Zorrototo** [comment]
Please use the forum for support. You most likely need to update the Panel, and the theme you're using, then force refreshing your browser cache.
