### ISSUE TITLE
Recaptcha not work

### ISSUE THREAD

**Issue by Cripix** [OpenGamePanel/OGP-Website#387]
Hello,

I have a problem with the recaptcha on your panel.

Indeed it does not work for a few weeks, I can connect to the panel without performing the captcha as on the gif (https://gyazo.com/be9f318799912444283f7533802a6ae8).

I made the last update and I tried with several themes and it's still the same problem.

Thank you in advance for your help !

**Comment by Zorrototo** [comment]
Admins do not need to validate the Captcha.

Use the forum for support.
