### ISSUE TITLE
Module Extras Error

### ISSUE THREAD

**Issue by lamjed001** [OpenGamePanel/OGP-Website#392]
Unable to get contents from: https://github.com/root/plex/commits/master.atom
OGP Version : 013a43c20985dcd0eb5e84f8029d580607caab93
![capture](https://user-images.githubusercontent.com/23016064/45928991-9ba81c80-bf43-11e8-99cd-60edee27b6d0.PNG)

**Comment by own3mall** [comment]
So, don't use your github username in the panel settings.  This feature is only for developers that know what they're doing.
