### ISSUE TITLE
Unturned Xml Request

### ISSUE THREAD

**Issue by buracat** [OpenGamePanel/OGP-Website#396]
I did but it doesn't work

https://pastebin.com/T5ZsV9HE

**Comment by rocco27** [comment]
Have ypu checked the forum, we have alot of xmls, isers shared and many of those should work.

**Comment by buracat** [comment]
Unfortunately none of them work. I don't think it's a problem in xml

**Comment by rocco27** [comment]
I will try to look and check xmls under Windows tonight.

**Comment by buracat** [comment]
Thanks

**Comment by rocco27** [comment]
I close this, because we already have open discuss about this on the forum.
