### ISSUE TITLE
Problem in the startup command line

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/OGP-Website#40]
I created a new ARK xml from the scratch. I was almost done then I found many variables don't work anymore in startup command line. I am sure all were fine before.

So thats the startup command line in the xml:
`<cli_template>%MAP%%IP%%PORT%%QUERY_PORT%%PLAYERS%%CONTROL_PASSWORD%%PDS%%PDI%%PDD%%PUS%%PUI%%PUD%%ASDN%%POP%%POPI%%PTA%?listen %CDO% %CID% %MMI% -server -log -servergamelog</cli_template>`

Thats the output from the Panel when I start the game server:
`ScorchedEarth_P?Multihome=MYIP?Port=MYPORT?QueryPort=MYQPORT?MaxPlayers=50?ServerAdminPassword=MYPASS%PDSPDIPDDPUSPUIPUDASDN%?PreventOfflinePvP=False?PreventOfflinePvPInterval=300?PreventTribeAlliances=False?listen -ClusterDirOverride=MYPATH -clusterid=MYID -server -log -servergamelog -ForceAllowCaveFlyers -NoTransferFromFiltering`

So I have a problem with few variables: %PDD%%PUS%%PUI%%PUD%%ASDN% those are not working until I insert a space before and after. If I do this then something is broken, if I hardwrite my configs whithout spaces everything work fine. What do you think?

Panel version: 87f5adbbad74bb83b96bc51b6516ceacd1447f42
Agent version: 8576f7a6dd5a2dd694d3ccc0c2f0e0120185bf5a

**Comment by own3mall** [comment]
I've not seen this issue.  Please see if you can get others to confirm.

**Comment by Zorrototo** [comment]
Share the XML at Pastebin.com and let us test.

**Comment by rocco27** [comment]
Sure I can do, but after work.

I played a little bit with the configs in the xml, changed the sequences, etc. and found more strange things. Well seems I found the way to get it work, but it is more strange.

So I will share soon and explain what I found...

**Comment by rocco27** [comment]
Here we go: [OGP ARK Linux Config](http://pastebin.com/Z1eGL6Za)

So as I said I found the way to get it work. This one works fine. No problem in the startup command line.
The problem comes when I do not define variables for 2 server params which use checkbox_key_value. If I remove IDs then many variables do not work in startup command line,
So original xml works, If I remove IDs from -NoTransferFromFiltering and -ForceAllowCaveFlyers then;

	TheIsland?Multihome=MYIP?Port=MYPORT?QueryPort=MYQPORT?MaxPlayers=4?ServerAdminPassword=MYPASSWORD%PDSPDIPDDPUSPUIPUDASDN%?PreventOfflinePvP=False?PreventOfflinePvPInterval=900?PreventTribeAlliances=False?listen -ClusterDirOverride=MYPATH -clusterid=1234567 %FACF% %NTFF% -server -log -servergamelog -ForceAllowCaveFlyers -NoTransferFromFiltering

%FACF% and %NTFF% not used right now because I removed the IDs, so those are correct.
But %PDSPDIPDDPUSPUIPUDASDN% are wrong, Here is the problem. If I remove -NoTransferFromFiltering and -ForceAllowCaveFlyers from the server_params, issue is gone. Why does it work like this?

**Comment by own3mall** [comment]
I'm still confused.  If you're not using NTFF and FACF, just remove them from the cli_template.  You should keep the IDs.  Why would you not want IDs on those params?  If removing IDs causes the problem, then you're not following the XML requirements, so any bugs are your problem?  

Or are you saying it shouldn't work this way?  Perhaps no ID provided shouldn't break the config, but then again, it's got an ID attribute for a reason.

Please let me know.  I'm just trying to understand

**Comment by rocco27** [comment]
I took the checkbox_key_value example from CS:GO xml. There is no ID for the parameter. I started to use in ARK with different parameters and got this %PDSPDIPDDPUSPUIPUDASDN% error. Then I tried what if I use IDs for those. Then the error disappeared. I could skip the error but the error (or the bug) is still there.

**Comment by own3mall** [comment]
Should be fixed in the latest version.  You were right.  Nice catch!  Thanks Rocco!

**Comment by own3mall** [comment]
Also, just for your reference, you should be able to use "{OGP_HOME_DIR}" as the start of the user's home server path in the "-ClusterDirOverride" option for your Ark config.  Hopefully that will prove useful?

**Comment by rocco27** [comment]
Thanks for your idea, but actually I need the path of the OGP_User_Files folder instead of the home path. I explain the situation. If I connect more servers together - it is called Cross-ARK Data Transfer or Cluster technology -, then all clustered game servers must to read and write character/dino/item datas from one specific folder. We can set anywhere, but I prefer to use a folder inside one of the game server, actually in the first. I set this folder to other game servers, then the moving between the game servers will be possible.
