### ISSUE TITLE
Unused placeholder should be removed

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#407]
Since FTP is not accessible as a main page and only from each game server own page as a button, it has been changed on the Dashboard page to not be accessible from there. There is now a placeholder which replaces the old FTP widget/section which in my opinion should be removed from this page as it kinda makes no sense at  all now as the section name and content is out of place (and reused from the default welcome message of Panel).

Here I commented this issue but nobody saw it I guess: https://github.com/OpenGamePanel/OGP-Website/commit/6dd1d883682dbcdfd584c9dc8c8756fede70e82e#commitcomment-30538666

I suggest to remove this whole section 'Username' (also remove all the related entries in DB, in widgets and widgets_users tables)

**Comment by own3mall** [comment]
I believe the FTP page is for managing all FTP accounts, is it not?  I guess I'm not exactly sure what the issue is.  Can you please post screenshots?

**Comment by Zorrototo** [comment]
There is no more FTP main page now no link to `home.php?m=ftp` anymore. As explained the block in dashboard does not refer to FTP anymore and was replaced with a placeholder but this placeholder seems out of place. https://www.dropbox.com/s/n7o6izp3fllfds7/Capture%20d%27%C3%A9cran%202019-01-24%2007.32.23.png?dl=0

You can see the change in the above link where I commented the commit.

FTP is now only accessible for the user from the game server page itself as a button, it made the menu uncluttered a little I think it was the goal back then.
