### ISSUE TITLE
Cron Admin shows ghost servers listed

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#408]
In the page Cron Admin, if you have previous existing servers Cron still in the scheduler.tasks file, the Cron Admin page will list them under wrong server, with the correct information but the server name.

The page Cron User properly list them all when you access as Admin this page, but the Cron Administration page displays of bigger list of servers with all the deleted servers Cron still listed under the wrong server.

example here is my scheduler.tasks file on Agent before I notice the issue:
``` 
36 05 * * * wget -qO- "http://www.com/ogp_api.php?gamemanager/restart&token=xxTOKENxx&ip=149.202.88.128&port=8888&mod_key=redorchestra2" --no-check-certificate > /dev/null 2>&1
35 05 * * * wget -qO- "http://www.com/ogp_api.php?gamemanager/restart&token=xxTOKENxx&ip=149.202.88.128&port=5665&mod_key=redorchestra2" --no-check-certificate > /dev/null 2>&1
34 05 * * * wget -qO- "http://www.com/ogp_api.php?gamemanager/restart&token=xxTOKENxx&ip=149.202.88.128&port=4565&mod_key=risingstorm2" --no-check-certificate > /dev/null 2>&1
33 05 * * * wget -qO- "http://www.com/ogp_api.php?gamemanager/restart&token=xxTOKENxx&ip=149.202.88.128&port=7690&mod_key=insurgencysandstorm" --no-check-certificate > /dev/null 2>&1
32 05 * * * wget -qO- "http://www.com/ogp_api.php?gamemanager/restart&token=xxTOKENxx&ip=149.202.88.128&port=7790&mod_key=insurgencysandstorm" --no-check-certificate > /dev/null 2>&1
31 05 * * * wget -qO- "http://www.com/ogp_api.php?gamemanager/restart&token=xxTOKENxx&ip=149.202.88.128&port=2565&mod_key=killingfloor2" --no-check-certificate > /dev/null 2>&1
59 05 * * * wget -qO- "http://www.com/ogp_api.php?gamemanager/stop&token=vxxTOKENxx&ip=149.202.88.128&port=64090&mod_key=MiscreatedDedicatedServer" --no-check-certificate > /dev/null 2>&1
00 06 * * * wget -qO- "http://www.com/ogp_api.php?gamemanager/start&token=xxTOKENxx&ip=149.202.88.128&port=64090&mod_key=MiscreatedDedicatedServer" --no-check-certificate > /dev/null 2>&1
```

In this example the Insurgency Sandstorm servers on port 7690 and 7790 do not exist anymore in my Panel. All others are still existing servers.
Cron user page `home.php?m=cron&p=user_cron` properly lists all existing servers and their cron.
Cron administration page `home.php?m=cron&p=cron` shows two more servers than it should, it lists these two non existent servers which still have a cron in scheduler.tasks file as the next server in scheduler.tasks file (it lists in total 3 Killing Floor 2 servers for 05:31 05:32 and 05:33 when only the one for 05:31 is an existing Killing Floor 2 server, the two others do not exist anymore in Panel, and are not even the proper listed game (originally Sandstorm servers) and port)

You can correctly remove these ghost cron from Cron Admin if you know the proper time of the cron to remove, it deletes the corresponding cron.

Not sure if this is intended but I don't think so because I can imagine a Panel where dozens of servers have been removed from Panel and the cron were not removed before, and then in Cron Admin it would be a mess to identify the proper cron to keep, and the ones to remove.

Maybe Cron Admin page should automatically remove the cron in scheduler.tasks of non existent game servers, or maybe when a server is removed from Panel it should check if corresponding cron(s) exist in scheduler.tasks and remove them to avoid this kind of issue in the future.

**Comment by own3mall** [comment]
Are you sure these cronjobs weren't created manually by the admin user?  Did the problem happen because you deleted the game server from the panel?  This needs to be examined further, and I'll need more info.
