### ISSUE TITLE
Startup line breaks server start - DayZSA

### ISSUE THREAD

**Issue by PrimusNZ** [OpenGamePanel/OGP-Website#409]
https://github.com/OpenGamePanel/OGP-Website/blob/f69c81890681f73efcf9b1a7ab8411f16a061ee2/modules/config_games/server_configs/dayz_win64.xml#L9

`-profiles="%HOME_PATH%/profiles"`
Should be
`-profiles=%HOME_PATH%\profiles` (Changing the forward slash to a backslash AND removing the quotes)

Otherwise server fails to start with:
```
 6:13:03 !!! [Inputs] Cannot open file for output ""C:\OGPAgent\home\cyg_server\OGP_User_Files\DayZSA/profiles"\Users\Survivor\Server.core.xml"
 6:13:03 !!! [Inputs] Cannot open file for output ""C:\OGPAgent\home\cyg_server\OGP_User_Files\DayZSA/profiles"\Users\Survivor\Server.dayz_preset_User.xml"
```
Also forward slashes are a linux thing, not windows - So the path is invalid.

**Comment by rocco27** [comment]
Agent is always running on Linux enciroment even if yoi are ising Windiws. When I released the xmk probably I tested on both OS and worked, I can't remember now. I will recheck once I get Windows for OGP to work.

**Comment by rocco27** [comment]
I am investigating now, and could get it work after a long time. I will come back with more feedback soon.

**Comment by rocco27** [comment]
I am testing now.

**Comment by rocco27** [comment]
Just found a strange thing on your side and leave a not: when you install OGP, you should always install to "C:\OGP" or "C:\OGP64" folders, this is written in the Easy Installer tutorial.

**Comment by own3mall** [comment]
Were you able to reproduce the problem, @rocco27 , or can this be closed?

**Comment by PrimusNZ** [comment]
OGP_HOME_000000032_STARTUP_SCR.BAT contains the following
```
@echo off
setlocal EnableDelayedExpansion
:TOP
set STARTTIME=%TIME: =0%
start /normal  /wait C:\OGPAgent\home\cyg_server\OGP_User_Files\DayZSA\DayZServer_x64.exe -config=serverDZ.cfg -port=2702 -profiles="C:\OGPAgent\home\cyg_server\OGP_User_Files\DayZSA/profiles" -dologs -adminlog -netlog   -cpuCount=2
set ENDTIME=%TIME: =0%
set "end=!ENDTIME:%time:~8,1%=%%100)*100+1!"  &  set "start=!STARTTIME:%time:~8,1%=%%100)*100+1!"
set /A "elap=((((10!end:%time:~2,1%=%%100)*60+1!%%100)-((((10!start:%time:~2,1%=%%100)*60+1!%%100)"
set /A "cc=elap%%100+100,elap/=100,ss=elap%%60+100,elap/=60,mm=elap%%60+100,hh=elap/60+100"
set hour=%hh:~1%
set minute=%mm:~1%
set second=%ss:~1%
if exist SERVER_STOPPED exit
IF "%hour%" == "00" IF "%minute%" == "00" IF %second% lss 15 exit
goto TOP
```

The following is being spat out by the server console. Which is saying it cannot find the profiles.
```
6:13:03 !!! [Inputs] Cannot open file for output ""C:\OGPAgent\home\cyg_server\OGP_User_Files\DayZSA/profiles"\Users\Survivor\Server.core.xml"
 6:13:03 !!! [Inputs] Cannot open file for output ""C:\OGPAgent\home\cyg_server\OGP_User_Files\DayZSA/profiles"\Users\Survivor\Server.dayz_preset_User.xml"
```

When you tested on yours, did you actually connect to the server? Or did you just start the process.
With the xml file in the repo, the server process starts, but the server itself does not initialize and complains with that error.
This does the same thing on my windows 10 machine with just the agent installed (To C:\OGP64), 2 machines with the exact same issue. But if you think nothing is broken here, i'll make changes to my local and blacklist the file.

**Comment by PrimusNZ** [comment]
Also, Why is the full path being specified in the `-profiles` flag? `-profiles=profiles` will also work just fine in the same way.

**Comment by rocco27** [comment]
I haven't connected by the game, cuz I could see the game server was online. It loaded everything without any errors and was ready to use. Server query also worked. Now I tried and I could connect and play on it.

Quotas can be important for the values in some cases in some game servers even if it is not written you have to use. Idk why need now, maybe cuz special characters like ':' or '\'. Idk. Usually we need for parameters where the space can be included in the values for example in hostnames (server names), where the space can be exist and it also brakes the value, so usually cut the server names shorter.

Here the server won't startup without quotas, slashtype also is doesn't matter on Windows, I tried. probably I forded to use Linux type before, cuz that was the one which worked under Wine. Now it is not working anymore, maybe never will, idk, so this can be changed, but quotas must have.

Honostly I don't care what Bohemia says, cuz offen happend I faced with wrong or even bad informations in the official docs for dedicated game servers. So I do what I have to do to get the game server work under OGP. About differences between a value inserted to qoutas or a parameter and value inserted to quotas, the second one even worst, ,make no sense, also never seen before in any type of game servers to be used. Idk how are the games from Bohemia, cuz I am not familiar with any. Never liked to managed...even if I could.

About profiles: let's check the tutorials (official also included) where they explains what is that and how to use the parameters: https://www.reddit.com/r/dayz/comments/9hamlp/the_dayz_server_owner_howto_and_faq/

For profile we can set the path of the game server, I used an extra folder named profiles to save all created files into one folder like a save folder, but it is not important, can be removed.

**Comment by own3mall** [comment]
@rocco27 @PrimusNZ Is there any update on this?

**Comment by rocco27** [comment]
I could not reproduce his issue on a fresh installed OGP on Windows 10.
I plan to build a server with Windows Server OS, where I can can do a new test with this game server, but it is still a plan, haven't started yet.

**Comment by rocco27** [comment]
The time has come and now I have a test server with Windows Server 2016.
I have some issues with network connection, but once I fix it I can install OGP Agent and test DayZ.

So very soon I will have more result.

**Comment by rocco27** [comment]
So after a long time finally I had enought free time and oppurtunity to test DayZ game server on Windows Server 2016.

I created a fresh installed OS with OGP Agent and everything is up-to-dated. I installed DayZ and the game server just works fine and without any issue. 👍 

Thanks for your cooperation! It was a great conversation with you. See you again next time!
