### ISSUE TITLE
[Feature Request] Toggleable Admin Emails

### ISSUE THREAD

**Issue by Codingale** [OpenGamePanel/OGP-Website#415]
I have two admins who don't want emails when someone registers; can this be added in as a user option or something?

The related lines are here:

https://github.com/OpenGamePanel/OGP-Website/blob/master/modules/register/register-exec.php#L41-L49

**Comment by own3mall** [comment]
It would be possible, but is it worth the effort?  You can always setup a client filter on the email account to delete these emails or move them elsewhere.  Or, if they don't want to get any email, you can always use an invalid email address.

**Comment by Codingale** [comment]
It's a feature request; they could set an invalid email but then if they forget the password they can't reset it easily. Filters could work but some services don't offer good filters. Though a email client should fix that.
Additionally, I notice they send the password in the email of the user who registered which means it could be insecure if I recall email isn't secure.. I could be wrong however and misunderstood the news story.

I don't quite see why everyone needs emailed about a new user registering when someone joins. If the billing module is setup it shouldn't matter right? I use OGP for hosting a few personal servers and some for friends.

**Comment by bojoer** [comment]
Related => https://github.com/OpenGamePanel/OGP-Website/issues/417
So yes I think the effort is more than worth to revise the mail sending...

**Comment by own3mall** [comment]
Wow, having a friend of yours open a similar request.  How cool.  Feel free to implement a solution and open a pull request if it's such a big deal to you.  :+1:

**Comment by own3mall** [comment]
You could always disable the registration module.  I don't use it.  Why would you allow random users to register?  I've never understood this functionality... usually, you'll want to create an account for game panel users after they've placed a paid order.

**Comment by own3mall** [comment]
Changes made in https://github.com/OpenGamePanel/OGP-Website/pull/420

Use "Receives email" user account setting.  Click on your username when logged into panel (or edit another user as admin).
