### ISSUE TITLE
Severe Security Risk

### ISSUE THREAD

**Issue by bojoer** [OpenGamePanel/OGP-Website#417]
When creating a new account both Username and **Password IN PLAIN** text are send in **ONE email**! This is not done. Or send it with two mails and preferable never send passwords but only reset links. This is a sever security risk... And no option to configure this or to disable sending mails on account creation.
Related => https://github.com/OpenGamePanel/OGP-Website/issues/415

**Comment by own3mall** [comment]
Passwords are routinely sent via email.  Emails can be protected and encrypted using TLS, so you're incorrect.  Anyways, this is related to "https://github.com/OpenGamePanel/OGP-Website/issues/415"

Maybe someone will fix it one day.

**Comment by own3mall** [comment]
Changes made in https://github.com/OpenGamePanel/OGP-Website/pull/420

Password no longer sent to user.
