### ISSUE TITLE
Installation Database Config Error

### ISSUE THREAD

**Issue by paulocrash** [OpenGamePanel/OGP-Website#418]
I arrive at the part of configuring the Database in the OGP but of the error, eg a print:
http://prntscr.com/n6o82c
http://prntscr.com/n6o87u

I used the command to display the password and put the password of the result, but nothing at all.

```
sudo mysql_secure_installation
```

What could it be, how can I correct it?

**Comment by Zorrototo** [comment]
use ip address of SQL server.

Use forum for support, only report real issues here when you can provide proper information regarding a bug.
