### ISSUE TITLE
squad_win64-updated needs update to v13-- exe files incorrect and filepathes and some "" to start server

### ISSUE THREAD

**Issue by ancientevil** [OpenGamePanel/OGP-Website#432]
As described above

**From SQ hosting discord**

Alpha 13 has been released to the Squad Dedicated Server. 

Alpha 13 will release in approx 12 hours but this is to ensure you have time to prepare servers.

PLEASE NOTE THE FOLLOWING:

- The server binary has changed name to SquadGameServer.exe
- You can no longer use quotes in the start script as paramters will be lost. An example of a NOT working script:

start SquadGameServer.exe "Port=7787 QueryPort=10000 FIXEDMAXPLAYERS=80 FIXEDMAXTICKRATE=50 RANDOM=NONE -fullcrashdump -log"

Instead, please use:

start SquadGameServer.exe Port=7787 QueryPort=10000 FIXEDMAXPLAYERS=80 FIXEDMAXTICKRATE=50 RANDOM=NONE -fullcrashdump -log

It is HEAVILY recommended that you always run with -fullcrashdump. If your server crashes, you will recieve a 2-5 GB crash dump that QA can use to debug why it happened.
If you're not using it, we can not determine why you crashed.

**Comment by ancientevil** [comment]
modules/config_games/server_configs/squad_win64.xml

**Comment by Zorrototo** [comment]
Thanks for info.

**Comment by rocco27** [comment]
Thanks, if it is not updated yet, I will do in this weekend.

**Comment by rocco27** [comment]
Xml files updated, reviewed once more and tested. Enjoy!

[Hotfixes May](https://github.com/OpenGamePanel/OGP-Website/pull/433)
