### ISSUE TITLE
outdated MTA:SA rsync

### ISSUE THREAD

**Issue by TAPL-93** [OpenGamePanel/OGP-Website#435]
The rsync still gives v1.3.4 while the latest version currently is 1.5.6

update request been ignored for unknown reason: https://www.opengamepanel.org/forum/viewthread.php?thread_id=5185

Also 64bit not included within the rsync.

**Comment by rocco27** [comment]
You can request any Rsync update for any games, but not here! It has own thread on the forum.

**Comment by TAPL-93** [comment]
rocco27 do not close things that does not concern you, the thread is abandoned since a year, i posted here to draw attention.

**Comment by Zorrototo** [comment]
Maybe posting in the forum thread to bump it may be a better idea? We have no access to the Rsync servers so the Rsync maintainer asked to post in the forum thread, if he didn't update it yet then post again. Thanks.

**Comment by TAPL-93** [comment]
> 
> 
> Maybe posting in the forum thread to bump it may be a better idea? We have no access to the Rsync servers so the Rsync maintainer asked to post in the forum thread, if he didn't update it yet then post again. Thanks.

Posted on August 20 2018. That's 315 days.
Posted on January 26 2019. That's 156 days.
Posted on June 22 2019. That's 9 days.

The thread is pinned up so it doesn't need bump.

**Comment by Zorrototo** [comment]
OK. That doesn't change anything, Post there. If it doesn't get updated soon and you desperately need and up to date Rsync server follow the tutorial to make your own it should not be that complicated.
It is not magical people need to invest their time to grab all the files, mix them up, and make sure it ends up in a working download. It is not critical to update the Rsync server and I guess if the maintainer saw it and didn't update, he probably have more important things to do. If he didn't see it I guess he'll update it later. Nothing more to do and say about it.
