### ISSUE TITLE
WINE installation in OGP wiki is wrong for Centos 7

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#447]
Seems like the WIKI is wrong about the installation procedure for WINE in Centos 7.
Seems like the vncserver package is wrong/incomplete as the command 'vncpasswd' is not found after installation. Seems like tiger-vnc-server is the vncserver package as 'vncpasswd' is working after installing this package.
Also I couldn't start VNC server or its service.
I couldn't go further in the tutorial as it was basically not working to this point and I'm really not a Centos fan and lack its basics.

**Comment by Zorrototo** [comment]
I replied in forum. Please use forum unless you're reporting an issue that breaks something that you can explain.

**Comment by own3mall** [comment]
@Zorrototo The documentation has been updated.  Can you please give it a try?

**Comment by Zorrototo** [comment]
It's all good now ;) Thanks for the Centos users.
