### ISSUE TITLE
Add php-mysqli as requirements during installation

### ISSUE THREAD

**Issue by henri9813** [OpenGamePanel/OGP-Website#455]
Hello,

Can you please add `mysqli` as a requirement in the installation page ? 

Indeed, in the install page, i have this:

![image](https://user-images.githubusercontent.com/4645967/70061725-1909fb00-15e5-11ea-847e-fac9ed526c7d.png)

Whereas in the second step, after typing my database configuration, i got this:

![image](https://user-images.githubusercontent.com/4645967/70061692-04c5fe00-15e5-11ea-96a9-c64d2aa758d6.png)

Best regards,

**Comment by own3mall** [comment]
Thanks.  :+1:

**Comment by henri9813** [comment]
Thanks, now, all it's perfect on my project ! :D 
https://github.com/henri9813/docker-opengamepanel
