### ISSUE TITLE
PHP message: PHP Warning:  htmlentities(): charset UTF8 not supported

### ISSUE THREAD

**Issue by JohnnyKing94** [OpenGamePanel/OGP-Website#458]
### Describe the bug

When trying to update OGP with php 7.3, i get **502 Bad Gateway** from Nginx. Checking the log, i see this error popping up multiple times.

```
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 FastCGI sent in stderr: "PHP message: PHP Warning:  htmlentities(): charset `UTF8' not supported, assuming utf-8 in /path/to/website/includes/functions.php on line 826
2019/12/10 11:18:10 [error] 22244#22244: *50408 upstream sent too big header while reading response header from upstream, client: 2001:b07:5d38:41eb:1db1:7636:9202:c159, server: website.tld, request: "POST /home.php?m=update&p=updating&version=d990444a74050462e842e34e1247fbbf6a2a004e HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm_website.tld.sock:", host: "website.tld", referrer: "https://website.tld/home.php?m=update"
```

### To Reproduce

1. Go to 'website.tld/home.php?m=update' with PHP-FPM 7.3
2. Try to update 

### Expected behavior

A 200 status page correctly loaded after the update.

### Server configuration

- Operating system: Ubuntu Linux 18.04.3 LTS
- Web server: nginx/1.16.1
- Database version: mysql  Ver 8.0.18 for Linux on x86_64 (MySQL Community Server - GPL)
- PHP version: php 7.3.12-1

### Client configuration

- Browser: Firefox 71.0 (64 bit)
- Operating system: Windows 10 Pro

### Additional context

I also checked if my **charset** was correctly set in **php.ini** and so it is. I have ```default_charset = "UTF-8"``` correctly set in the file and the image can speak for itself.

![Screenshot 2019-12-10 11 46 58](https://user-images.githubusercontent.com/4331193/70523237-e317ca00-1b42-11ea-8c10-236c7e168b39.png)

**Comment by own3mall** [comment]
Not related to OGP code.  

Something (maybe an .htaccess file) or another configuration setting is incorrect.

https://forum.opencart.com/viewtopic.php?t=201801

Please search online for possible resolutions.

**Comment by JohnnyKing94** [comment]
@own3mall Maybe I found the problem... I will know for sure on the next update you release in order to trigger the updating. Someone of my admins used the override charset function in the Panel Settings and typed UTF8 instead of UTF-8, cause he probably read the wrong message in the info tooltip: ```UTF8, ISO, ASCII, etc... Overrides the character encoding defined in language files. Leave it...```. The correct message would be ```UTF-8, ISO, ASCII etc```. I propose to edit all the language setting files with the fixed charset info or to add the list of charsets as link in the tooltip. This will be fine: https://www.php.net/manual/en/mbstring.supported-encodings.php

This is the line I mean: https://github.com/OpenGamePanel/OGP-Website/blob/54178195092620614b3cacbd1a31355ca7f6bf2c/lang/English/modules/settings.php#L48

**Comment by own3mall** [comment]
@JohnnyKing94 Agreed

@Zorrototo Could you please update that sting in Transifex when you get a chance?  Thank you!

**Comment by Zorrototo** [comment]
Yes we could and I will, but the problem here is someone using an overriding character encoding settings and putting an invalid setting. Anyway if it's wrong in the tooltip it's wrong and needs fixing. By the way I suggested a long time ago to completely get rid of this unneeded setting a while back, because since the new way we manage languages, we now have the character encoding defined on UTF-8 in all language files and if someone wants to use another character encoding then he may do it by editing the language file. I don't know maybe I'm overlooking something with this parameter but it seems not needed anymore (unless you want a different character encoding in your language fie and globally in Panel, which I don't believe as it would surely create problems with the lang strings then, I don't know :D)

**Comment by own3mall** [comment]
@Zorrototo I always forget lol... if you want, I can do it.

@JohnnyKing94 was there a reason why you set the encoding?

@Zorrototo - I will look into removing this setting as you suggested.

**Comment by Zorrototo** [comment]
Already done (and fixed as the web editor added some "FR 9+" characters in the file o_O...)
Transifex will catch up soon then I'll send back to GitHub ASAP.

**Comment by JohnnyKing94** [comment]
@own3mall no reason at all... some of my admins did, probably he misread the info message and i didnt even realize it until i stepped into that page ad saw the parameter set. For the moment I left it black to use the default one by the php engine.

I agree to remove them btw, also "Time Zone" need to be removed... they're "useless"... you can already control them with the php ini settings in global or local (per site) way.

**Comment by JohnnyKing94** [comment]
Btw I saw the update and I triggered it... now everything works as it should, updated and the installing update page showed up... nothing breaks anymore. Btw if you wanna keep the message, it needs to be fixed for each language of OGP. You just edited for the English one.

https://github.com/OpenGamePanel/OGP-Website/tree/54178195092620614b3cacbd1a31355ca7f6bf2c/lang

**Comment by Zorrototo** [comment]
Yes I just edited the English file, that's correct, maybe read what I wrote above then? It is fixed in all languages now. It is up to people in charge of their respective language to update the string for it to be in the proper language, it defaulted to English for now. That's how it works.

Time zones are not useless though. They are used for example in the Cron module.

**Comment by own3mall** [comment]
@Zorrototo It's been removed.  https://github.com/OpenGamePanel/OGP-Website/commit/43ab74e82a9068b4efe848fc925b2b7cd29fb19c

@JohnnyKing94 Thanks for helping us clean this up.  :+1:
