### ISSUE TITLE
To be looked at Unturned XMLs

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#463]
Seems like the Unturned XMLs need to be updated to use the new AppID https://www.opengamepanel.org/forum/viewthread.php?thread_id=7190#post_38125

**Comment by own3mall** [comment]
Should be fixed in latest.  https://github.com/OpenGamePanel/OGP-Website/pull/467

Hope it's all good.

**Comment by Zorrototo** [comment]
I was going to do it but as I had computer issues since early this month I halted everything, I just got my real computer back yesterday.

**Comment by Zorrototo** [comment]
Also there were four Unturned XMLs, and also by using the helper script file to start the server, now it needs also to lock the real executable file.. I think I will redo it all with proper environment variables in the XML and all, that was the plan now I remember. Reopening, will do it later next week.

**Comment by Zorrototo** [comment]
Actually couldn't find time to redo them, it is good enough for now. Noted in my low priority list. Reclosing.
