### ISSUE TITLE
FTP Users

### ISSUE THREAD

**Issue by kreator-eb** [OpenGamePanel/OGP-Website#465]
Dont think I saw an issue for this being open before so I will write one, for quite some time it is not possible to edit the ftp accounts.

In Admin / FTP Users section where you create ftp users with selected directories you are not able to change the details after they are being made, the button does nothing, it just refreshes the site.

![image](https://user-images.githubusercontent.com/36107078/73119713-32388380-3f66-11ea-9f62-2cbdde412ebe.png)

This persists for quite some time, also my panel has been updated today, version: 99b077817b9451eb5c0e9b4dcc0aab5569c56ba8
and the issue still persists, just so you know its not a problem with a version or something, and the issue persists across all themes.

I asume [this ](https://github.com/OpenGamePanel/OGP-Website/blob/master/modules/ftp/ftp_admin.php)is the file in question, specific code "edit_ftp_user".

**Comment by Zorrototo** [comment]
it works.

**Comment by kreator-eb** [comment]
>  it works.
What version and theme, I dont have anything modified regular centos7 ogp with SimpleBootstrap, everything is fine except that modification option.

**Comment by Zorrototo** [comment]
No, no no, do this the other way around, YOU, use official OGP.

**Comment by kreator-eb** [comment]
> and the issue persists across all themes.

Already wrote that its the same across all themes, and had the same issue across a few different versions of ogp as well.

**Comment by Zorrototo** [comment]
Then I'm telling you. It works. Anyway you don't report a problem with an extra theme but with official OGP. If you need support for an issue on your end, use the forum.

**Comment by kreator-eb** [comment]
Well thats why I said its the same on every theme, including official.

> If you need support for an issue on your end, use the forum.

Idk what could be the cause, do you have at least an rough idea, will look myself, so I dont need to open a whole post for it.

**Comment by Zorrototo** [comment]
Look in your log files. https://www.opengamepanel.org/forum/viewthread.php?thread_id=1950

**Comment by kreator-eb** [comment]
No errors sadly, nor on the front end or back end, couldn't find any thread with similar problem either, quite odd since everything is working perfectly except that one thing eh. Also tried other browsers but its the same, if I find a solution I will post here just to let others know.
