### ISSUE TITLE
Bad Dashboard URL reference paths - PHP 7.4.x

### ISSUE THREAD

**Issue by SugarD-x** [OpenGamePanel/OGP-Website#468]
In Dashboard.php:

`js/jquery/plugins/jquery.json-2.3.min.js` <- Line 1
`js/modules/dashboard.js` <- Line 2

These paths are sought by the page as being within the same directory, rather than the base installation path, which causes the dashboard to break in PHP 7.4.x. I believe it is the cause of this report:
https://www.opengamepanel.org/forum/viewthread.php?thread_id=7195

Because these aren't being loaded properly on the dashboard, it breaks the entire page. This doesn't happen on some of the other pages, as documented in the forum topic. My best guess is that a recent version of PHP changed how relative paths are handled, as there is documentation online of similar problems within other websites using relative paths with later versions of PHP.

**Comment by own3mall** [comment]
@SugarD-x 

I upgraded to PHP 7.4, and I haven't noticed any problems.  The scripts are referenced using local paths.  This has nothing to do with PHP as I initially suspected.  Configure your webserver properly.
