### ISSUE TITLE
Where is this EASY install ?

### ISSUE THREAD

**Issue by BestNoob** [OpenGamePanel/OGP-Website#475]
Guys for real, when i start a setup and everything is going automaticly i need to trust you that you dont change essential things in my system.

And installing/starting a MySQL Database without my permission is not the way.
My own MySQL Server is not running on standard ports but your Setup blocks the service ?!

And whats with the users who are running it on standard ports ? You dont care ?

... thats really not Easy when it does more work than it helps.

Why not asking for integration into a already existing MySQL Apache etc. installation ?
Why no auto detecting if such stuff already exist ?

**Comment by own3mall** [comment]
It is recommended that you dedicate the server for OGP.  Do not install anything other than OGP on the server if you're using the **easy installers for OGP**.  This advice applies for both the Windows and Linux versions of OGP.  If you know what you're doing, OGP can be installed manually on Linux.  Windows currently requires cygwin.  There is no other way to run it in Windows.
