### ISSUE TITLE
Php 7.3 Update

### ISSUE THREAD

**Issue by McDowel06** [OpenGamePanel/OGP-Website#479]
Bonjour, j'ai un problème avec mon PHP 7.3

Le module : xmlrpc est pas compatible 

j'ai installer xmlrpc2 via pearphp mais cela ne fonctionne pas 

pouvez vous m'aider ? je suis bloqué a l’installation .

je n'es aucun moyens de passer a PHP 7.0 car mon hébergeur me dit qu'il est plus supporté par les mise a jour de sécurité ...

Merci d'avance pour votre réponses :)

**Comment by Zorrototo** [comment]
This is the GitHub for OGP issues, not for you hosting company issues. Go to the forum if you want some random help.
