### ISSUE TITLE
Check expire seems to throw SQL warning/error 

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#480]
Check expire function (.../index.php?m=user_games&p=check_expire page) seems to throw SQL warning/error with recent MySQL standards (see here for reference https://www.opengamepanel.org/forum/viewthread.php?thread_id=7312&pid=38579#post_38580)

`Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ogp_panel.g.group_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

**Comment by Zorrototo** [comment]
I think this is the relevant info from the manual of MySQL 5.7+ https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

**Comment by own3mall** [comment]
The solution is to disable that setting.  The new SQL modes suck.

https://stackoverflow.com/questions/23921117/disable-only-full-group-by

Too many SQL changes were made that break older code.  Unfortunately, I've run into problems like this, and their new default is wrong.  :|
