### ISSUE TITLE
SteamCMD overloading machine with download

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#486]
This issue is for both Agents, and the Panel.

When you proceed to a game server install with SteamCMD, there is a big issue which is that SteamCMD simply use all the machine bandwidth (when Steam servers are not overloaded and send full speed), resulting in all game servers on the machine lagging a lot, people having 500 ping, things like that.

Apparently there is a SteamCMD command line parameter to throttle the downloads, I think this should be integrated in each Agent configuration (in the Administration -> Servers -> Edit Agent page) in Panel to take advantage of this parameter and limit per Agent machine the maximum download rate for SteamCMD (various machines/Agents have different capabilities so I think this should be an Agent setting not a global setting).

Official doc: https://developer.valvesoftware.com/wiki/Command_Line_Options#Command-line_parameters_4 the line "set_download_throttle"

I discovered this parameter from this forum thread https://www.opengamepanel.org/forum/viewthread.php?thread_id=7340

Hope this could get tested and integrated soon as this has been an issue for me (and I guess for everyone) since forever.

**Comment by own3mall** [comment]
@Zorrototo I was thinking this could be set globally once in the panel settings... even though it is now an agent setting... each agent would pull this setting and limit it to the rate set (globally)... easiest way to implement for now.  See my recent changes to agent and web for more info.

**Comment by Zorrototo** [comment]
I don't know what's best, I'm all for an Agent setting, even if it would mean not accessible from Panel, directly in Agent config file if that can simplify things.

While a simple global setting would work, in the end it would not really fix the issue if you have huge discrepancies in machines' bandwidth, for example you have a 100MB server and a 500MB server, what will you set the limit at? 50MB? that would work well for the 100MB server but very limiting for the 500MB one.

Or maybe what could also work (but it makes more work to do), would be a global setting in Panel accessible for the Agent from API, but with an override possible directly in the Agent config file? 

Just suggestions but overall I think this setting should exist in some way. You're the boss I'm sure you'll figure what's best and most convenient to do :+1:

**Comment by own3mall** [comment]
Implemented

**Comment by Zorrototo** [comment]
Great! Thanks! Will try it soon :+1:
