### ISSUE TITLE
ftp module logo

### ISSUE THREAD

**Issue by smalls89** [OpenGamePanel/OGP-Website#49]
the ftp module logo points to a 'shinra' skin for the only thing in that location in 'blue' skin

![3d8031202fee4a7d0a88cdaa9ce4976a 1](https://cloud.githubusercontent.com/assets/4153529/23304421/5dafd184-fa5f-11e6-90e9-de63fc6dc9ce.png)

**Comment by smalls89** [comment]
[Found this](http://www.net2ftp.com/download/net2ftp_v1.0.zip) it has the theme...

**Comment by Zorrototo** [comment]
skins/blue/images/img/logo.png it is already here, a simple error in the page itself.

**Comment by own3mall** [comment]
Fixed
