### ISSUE TITLE
Stop expired server

### ISSUE THREAD

**Issue by m1lfman** [OpenGamePanel/OGP-Website#493]
Thread: https://www.opengamepanel.org/forum/viewthread.php?thread_id=7362

When Cron delete expired server, files are deleted fine but won't stop server process.
So, server is still running, we need to kill PID o stop it.
Generally problem is in exec_operation function:
```
$isAdmin = $db->isAdmin( $_SESSION['user_id'] );
   if($isAdmin)
      $home_info = $db->getGameHome($home_id);
   else
      $home_info = $db->getUserGameHome($_SESSION['user_id'],$home_id);
```

There is problem, because we don't have $_SESSION['user_id'].
I'm fixed this by creating new file with exec operation and deleted this if statements. Also, I'm replaced new file with old in check_expire_date function.

**Comment by own3mall** [comment]
Should be fixed in the latest code.  Please try and confirm.
