### ISSUE TITLE
GameQ - Minecraft problem

### ISSUE THREAD

**Issue by dension0** [OpenGamePanel/OGP-Website#495]
Hi,
Server Cent os 7 64 bit
ogp agent updated version, fressh install (according with this site tutorial).
Java 14 installed
Web website (GUI) 495b67e5b84a81189f984750e4c30802a2183604 updated version
For example CSGO started everything fine, Cs 1.6 started everything fine, MTA started everything fine, Minecraft started but:
- server can start without error but the GUI say:
"Server is running, but its not responding,
there might be a some kind of problem and you might want to Stop server.."
Everybody can connect to game and can see game status or can play
RCON can accept command from GUI and can get the ansver from server.
NO DSI can generate.
All neded port opened beetwen Panel and Agent server.
If I make an php into root dir of my website where is my OGP Panel runing with following content:
`<?php
require_once 'protocol/GameQ/GameQ.php';
    $gq = new GameQ();
    $gq->addServer(array(
       'id' => 'server',
       'type' => 'minecraft', // Counter-Strike: Source
       'host' => '***.***.***.***:41752',
    ));
   
    $results = $gq->requestData(); // Returns an array of results
   
    print_r($results);

?>`
I get following respond:
`Array ( [server] => Array ( [hostname] => Minecraft [gametype] => SMP [game_id] => MINECRAFT [version] => 1.15.2 [plugins] => [map] => world [numplayers] => 0 [maxplayers] => 5 [hostport] => 41751 [hostip] => ***.***.***.*** [gq_online] => 1 [gq_address] => ***.***.***.*** [gq_port] => 41752 [gq_protocol] => gamespy3 [gq_type] => minecraft [gq_name] => Minecraft [gq_transport] => udp [gq_joinlink] => ) )`
As I see the GameQ.php file working well.
As I see 2 files use this file:
modules/gamemanage/ref_servermonitor.php
modules/dashboard/query_ref.php

As I see the GameQ.php file do not get the right data to make connection to remote server and get respond, or can not able to write respond into sql of OGP Panel table: cache.
Now sql of OGP Panel (not Minecraft or aby game) cache table for this server content is:
`date_timestamp   ip_id   port     server_status_cache
1591136864        1        41751  []`

So I would like to get some advance how can I correct this error.

Also the connection beetwen Panel and Agent exist and good. They can communicate eachothers.
The Panel can not able to get datas or write into database the datas with GameQ.php
The GameQ.php can get right and correct data from Agent via own write script.
I useing base template.
Please help me to cerrect this error.
Bestregards,

**Comment by Zorrototo** [comment]
Reference: https://www.opengamepanel.org/forum/viewthread.php?thread_id=7370#post_38834

**Comment by own3mall** [comment]
Someone will have to test and verify that there is a problem.  I may try to do it at some point...

**Comment by dension0** [comment]
I reinstalled my whole system: OGP Panel and Agent too.
The problem is exist and same. At Minecraft game the Gameq do not working. But if I make an php and call from that, I recevie datas from agent.
Op. system both of on both of server: VPS, CENTOS 7 64 bit, VESTACP NGINX and APCAHE, CSF firewall. Any game wich is do not use Gameq working right (tested with CSGO, CS1.6, MTA)

**Comment by own3mall** [comment]
@dension0 Does GameQ V3 help with your problem?  If not, please tell me step by step how I can reproduce.
