### ISSUE TITLE
Hebrew translation problem

### ISSUE THREAD

**Issue by aamiel1** [OpenGamePanel/OGP-Website#502]
Hi,

Please fix the line in OGP-Website/lang/Hebrew(Israel)/global.php
from:
define('OGP_LANG_lang_charset', "קידוד UTF-8");
to:
define('OGP_LANG_lang_charset', "UTF-8");

Thanks,

**Comment by Zorrototo** [comment]
Thanks for reporting this is a BIG issue, the translator was really careless I don't understand how that slipped.

**Comment by Zorrototo** [comment]
Should be fixed in a few minutes.

**Comment by aamiel1** [comment]
All my pleasure,
 I also started to make many repairs to the Hebrew translation.
