### ISSUE TITLE
Erroneous "Failed to start the remote server. Error code: -1"

### ISSUE THREAD

**Issue by smalls89** [OpenGamePanel/OGP-Website#51]
when starting wurm server with a large map, the panel returns this error "Failed to start the remote server. Error code: -1" however the server actually starts. If the server is started with a smaller map it operates just fine.

I suspect it has something to do with the wurm server hanging and being momentarily unresponsive.

**Comment by Zorrototo** [comment]
can you give step to reproduce this?

**Comment by own3mall** [comment]
Try adjusting the agent timeout under servers.  Let us know if that helps.

**Comment by smalls89** [comment]
step to reproduce, start a wurm server with a valid 8kx8k map and it will do it every time, it wont do it on a 4kx4k

changed wait time to 10s, fixed it

**Comment by Zorrototo** [comment]
If I asked.... this is because I don't know, so how to start with a valid 8kX8k map? Anyway if you fixed, there's no issue.

**Comment by smalls89** [comment]
There are various maps you can dl, making one is a pain and takes a few hours, but, link to the generator if you want to tinker http://forum.wurmonline.com/index.php?/topic/133610-map-generator-28/
