### ISSUE TITLE
Colony survival-colonyserver.exe new exefilename

### ISSUE THREAD

**Issue by ancientevil** [OpenGamePanel/OGP-Website#512]
Old exe name is=colonyserverdedicated.exe
New exe name seems to be colonyserver.exe

Cheers!

**Comment by Zorrototo** [comment]
Fixed.

For info, lifetime max concurrent players (in three past years): 3

**Comment by ancientevil** [comment]
Thanks- a real fun game though- now 250 players play it in steamcharts :=)

**Comment by Zorrototo** [comment]
Yeah I though I was on the game page on SteamDB but I was still on the server page :)
