### ISSUE TITLE
squad_win64.xml and linux64

### ISSUE THREAD

**Issue by ancientevil** [OpenGamePanel/OGP-Website#513]
The game will be released in **near future** the ability for 100 players.
That means i think these files need to be changed for max players 100

Cheers and awesome work with OGP!

/ANcientevil_one

**Comment by ancientevil** [comment]
100 players= licensed server from OWI :=)

**Comment by Zorrototo** [comment]
You mean it is servers provided by the developer? in this case then it doesn't need any change as you wouldn't rent the server to them.

**Comment by ancientevil** [comment]
No, for example our community server is selfhosted and running ogp and official squadserver. 

We have an official license and in very near future we have applied for 100 player license. 

That means server pop will increase to 100 players

**Comment by ancientevil** [comment]
As we are prohibited to announce full changes here before release by OWI my post was a heads up for the player change of servers atleast.

**Comment by ancientevil** [comment]
@Zorrototo 1.0 release is today 18.00 UTC= 100 players cap

**Comment by Zorrototo** [comment]
OK I'll update the player count.

**Comment by Zorrototo** [comment]
Done.
