### ISSUE TITLE
FTP everything lol

### ISSUE THREAD

**Issue by smalls89** [OpenGamePanel/OGP-Website#52]
#49 I linked the theme in this issue as I noticed a decent amount of references to the shinra theme that have different link locations in the blue theme
![90a59fb80ad3e7b66b2ccf00b538b57a 1](https://cloud.githubusercontent.com/assets/4153529/23330089/6c1e4fb4-fb0b-11e6-878b-a9c5c387c94a.png)

**Comment by smalls89** [comment]
all links do nothing as well

**Comment by Zorrototo** [comment]
no.

what are you talking about?

**Comment by Zorrototo** [comment]
My crystal ball magic powers tell me you remove the blue skin folder. Please put back everything you deleted in the module and close the issue lol.

**Comment by own3mall** [comment]
I can't reproduce.

**Comment by smalls89** [comment]
i didnt delete anything nor change anything, i just ran the update and this is what i ended up with... 
![228123c3df8ce4003ad9a748d997c6f5 1](https://cloud.githubusercontent.com/assets/4153529/23352166/37fef356-fc8b-11e6-8ceb-daee20b4dd8d.png)

**Comment by smalls89** [comment]
hust updated to d98a0e84f1f9dddc9ef92fe2e4b161c9ac3c1155 and same thing

**Comment by Zorrototo** [comment]
CONNECTION REFUSED it says, verify on your webserver that the files are here, and see why your webserver refuse to you the connection I guess. Panel has no problem.

**Comment by own3mall** [comment]
oooo are you running your OGP panel behind a SSL certificate?

**Comment by smalls89** [comment]
no ssl yet

Im using iis reverse proxy. I found the ftp window has a redirect to the skin that wasnt playing nice...

![a5536671b5e5118dffb37a68506eff5a 1](https://cloud.githubusercontent.com/assets/4153529/23401650/10713482-fd6e-11e6-92a7-2a321af3168c.png)

**Comment by Zorrototo** [comment]
Your image doesn't work, error 503...

**Comment by smalls89** [comment]
Wat? Image should be fine...

**Comment by Zorrototo** [comment]
now it shows.
