### ISSUE TITLE
File Manager doesn't works properly with folder names that have brackets

### ISSUE THREAD

**Issue by TAPL-93** [OpenGamePanel/OGP-Website#520]
Folder names such as [test] appear as test and can't enter, rename, remove or move.

Move window shows the actual names of the folders.
![ogpFM](https://user-images.githubusercontent.com/11547491/103134576-382d6c00-46c3-11eb-8cd4-8f957bf9ad3e.jpg)

**Comment by own3mall** [comment]
Please read or search the forums next time.

https://opengamepanel.org/forum/viewthread.php?thread_id=7410
