### ISSUE TITLE
Squad updated to V 2.0- New configfiles

### ISSUE THREAD

**Issue by ancientevil** [OpenGamePanel/OGP-Website#537]
maprotation obsolete--->changed to LayerRotation.cfg

more conrfigs added for example below

They are planning to add votes in near future still these files do exist when installing server
CustomOptions.cfg 
ExcludedFactions.cfg 
ExcludedFactionSetups.cfg 
ExcludedLayers.cfg 
ExcludedLevels.cfg
LevelRotation.cfg
VoteConfig.cfg

**Comment by Zorrototo** [comment]
Please explain the required changes more in details

**Comment by ancientevil** [comment]
**Well maps is in a different style now**

maprotation obsolete--->changed to LayerRotation.cfg in this maps are specified with layers for example 

CAF_GooseBay_Skirmish_v1 exact this map+layer
Albasrah_AAS_v1
Gorodok_RAAS_v1

level rotation.cfg is
CAF_GooseBay but the layer is random and can be set in server.cfg



server.cfg changes as below


ServerName="SERVERNAME"

// Control visibility in the server browser
ShouldAdvertise=true

// Set the server to LAN mode
IsLANMatch=false

// Max player count on the server
MaxPlayers=100

// Number of reserved slots for admins / members 
NumReservedSlots=0

// Size of the server queuing, for regular user 
PublicQueueLimit=25

// Map rotation mode: it can be 
// LevelList(use order in level rotation config file)
// LayerList (use order in layer rotation config file) 
// or 
// LevelList_Randomized
// LayerList_Randomized
// which are randomized version of previous options
MapRotationMode=LayerList

// Should the Map/Layer rotations list be randomized at start?
RandomizeAtStart=false

// Should Faction be voted for on generic layers? Randomized if false. 
UseVoteFactions=false

// Should next Map be voted for at end of round?
UseVoteLevel=false

// Should next Layer be voted for at end of round?
UseVoteLayer=false

// Completly Allow or Disallow Team change to all players. Only user with Level_Balance access level can bypass this flag
AllowTeamChanges=true

// If set to false, players can change teams regardless of team balance. Otherwise, the NumPlayersDiffForTeamChanges Value is used
PreventTeamChangeIfUnbalanced=true

// Maximum Allowed difference in player count between teams. This takes into account the team the player leaves and the team the player joins
NumPlayersDiffForTeamChanges=3

RejoinSquadDelayAfterKick=180
RecordDemos=false
ServerMessageInterval=300

// Forces the server to do non-seamless travel (disconnect when changing maps) every X seconds
// ForceNonSeamlessTravelIntervalSeconds=43200

// The following are required for Licensed servers, but can be changed for non-licensed servers
TKAutoKickEnabled=true
VehicleKitRequirementDisabled=false
AllowCommunityAdminAccess=true

// Only Offworld Industries developers are admins
AllowDevProfiling=true

AllowQA=true

// The below commands are optional for all servers
VehicleClaimingDisabled=false

**Comment by Zorrototo** [comment]
OK thanks. I'm still not sure what it means for the current XML. I can see this line is now obsolete https://github.com/OpenGamePanel/OGP-Website/blob/master/modules/config_games/server_configs/squad_linux64.xml#L85 but besides that, is it a request to add new settings to the XML?

The only relevant change I see is needed for now is to change the map rotation file name.

**Comment by ancientevil** [comment]
> OK thanks. I'm still not sure what it means for the current XML. I can see this line is now obsolete https://github.com/OpenGamePanel/OGP-Website/blob/master/modules/config_games/server_configs/squad_linux64.xml#L85 but besides that, is it a request to add new settings to the XML?
> 
> The only relevant change I see is needed for now is to change the map rotation file name.

thats correct- the rest can manually be changed in server.cfg

please change also win64 file

Thanks for doing a great job.

We are using this for administering a total of 28 server in our community and our squadserver is top5 europe :)

**Comment by Zorrototo** [comment]
https://github.com/OpenGamePanel/OGP-Website/pull/545/files

We can add other config files to the Edit Config File part, but I don't personally use Squad and can't tell what is relevant. You can make PR yourself to improve the XML https://www.opengamepanel.org/forum/viewthread.php?thread_id=5047
