### ISSUE TITLE
Panel php8.0 ready?

### ISSUE THREAD

**Issue by H4nSolo** [OpenGamePanel/OGP-Website#548]
First of all, sorry that I am not reporting this in the forum.

System: Ubuntu Linux 18.04.4
Web server: Apache2
Panel Version: c3005feed41d44dfcfe2e073ba8e6a9d28cb97a4

Yesterday I updated my web server to the php8.0 version.
Since the update I now unfortunately have template problems on various pages.

> Fatal error: Uncaught Error: Undefined constant "statistics" in /var/customers/webs/domain/panel/modules/dashboard/dashboard.php:124 Stack trace: # 0 / var / customers / webs / domain / panel / includes / navig.php (106): exec_ogp_module () # 1 /var/customers/webs/domain/panel/includes/navig.php(27): navigation () # 2 / var / customers / webs / domain / panel / home. php (146): include ('...') # 3 /var/customers/webs/domain/panel/home.php(377): heading () # 4 / var / customers / webs / domain / panel / home .php (77): ogpHome () # 5 {main} thrown in /var/customers/webs/domain/panel/modules/dashboard/dashboard.php on line 124

Is the panel capable of php8.0 at all or am I now really forced to downgrade to an older php version and thereby make other websites unusable?

I hope someone can help me with this.

**Comment by AlexanderCurl** [comment]
On ubuntu you can use multiple php versions on the same time. I suggest to stick on php 7.2 or 7.4 for the time being with the panel, and you can run whatever you need with php8.0 on the other sites.

**Comment by own3mall** [comment]
PHP 8 is not officially supported.  @H4nSolo, your issue has been fixed by the latest update.  If you notice any other errors related to PHP 8, please open a new issue.
