### ISSUE TITLE
MCP - Theme

### ISSUE THREAD

**Issue by P34NUT85** [OpenGamePanel/OGP-Website#553]
Hello own3mall, 

I was hoping you might be able to point me in the right direction on where I can find information about how to get the MCP Theme for the Open Game Panel added? so users can select and add the theme after installing the Open Game Panel. I have plans to contribute some modules to this project, with some extra themes etc, and would be really helpful if I knew the process which the ZPE-Online contributions need to go through before users are able to select and add them.

Thanks for any info you are able to provide on this. 

Kind Regard's

Michael White

**Comment by own3mall** [comment]
Create a GitHub repository under your account named something like:

Theme-MCP

The repository name must begin with "Theme-"

Store your theme source code files in this repository. 

Send me your github username, and I will test your theme by pointing a test OGP panel instance to pull from your github repository (panel settings --- github username). 

If it seems OK, I will add an official repository for it and make you an admin for it.

OwN
