### ISSUE TITLE
content no found

### ISSUE THREAD

**Issue by xxqs01** [OpenGamePanel/OGP-Website#554]
Hello friends, the panel is very good and I have it hosted in my dedicated with cpanel, it is going great but I have an error and it is that when I select the api option I get that CONTENT NOT FOUND error, how could it be solved? the panel in its latest version

https://cdn.discordapp.com/attachments/503288427723358209/845831100139307009/panel.png

**Comment by Zorrototo** [comment]
Support request should be made on the OGP forum: https://www.opengamepanel.org/forum
Here are the rules to open a support request: https://www.opengamepanel.org/forum/viewthread.php?thread_id=1950
