### ISSUE TITLE
[Enhancement] Requesting server status showing CPU/RAM usage for user frontend

### ISSUE THREAD

**Issue by ner00** [OpenGamePanel/OGP-Website#563]
It would be pretty nice to see resources used by a given server, something similar to https://github.com/OpenGamePanel/OGP-Website/tree/master/modules/status/status.php but which would be available to the end user in https://github.com/OpenGamePanel/OGP-Website/blob/master/modules/gamemanager/server_monitor.php

This would only show resources being used by the user's server(s) and nothing else.

Implementing this for a server that runs the panel and the game servers seems somewhat more easy in theory, but doing so for different servers through the agent doesn't looks as straight-forward.

Please consider implementing this.

**Comment by Bebiano86** [comment]
yes I would very much like to see this implemented.

**Comment by own3mall** [comment]
Please post feature requests in the forum.  

https://opengamepanel.org/forum/viewforum.php?forum_id=4

It would be interesting to discuss in the forums why you think the end user would be interested in seeing the amount of resources he's using on the server.  I could see showing per-user server resource usage to the admin in the panel, but not the end user.

**Comment by ner00** [comment]
@own3mall It seems like something along these lines was suggested a year ago in the forum, but apparently it wasn't specific enough or wasn't appealing enough: https://www.opengamepanel.org/forum/viewthread.php?thread_id=7393

Seeing per-user resource usage seems to me as much of interest as per-gameserver resource usage. Given such implementation, whether the admin is the only one able to see it or not boils down to semantics; you can allow one or the other, or both.

**Comment by Bebiano86** [comment]
I think it is important for the user to know how much ram or cpu he is using to be able to optimize his server in case he is using mods etc...

As for posting on the forum there have been more people asking but no admin has ever responded.
