### ISSUE TITLE
Please help with a bug in the plugin list

### ISSUE THREAD

**Issue by IGNRexI** [OpenGamePanel/OGP-Website#564]
please help me.
and it will be great if you set it as listed by default. In general, add-ons are listed in cs 1.6 or csgo panels. but I use open game panel because it is the best choice because they charge a lot. I made myself a built-in design.
I've set the list of plugins and maps to be listed like this but I'm getting an 'invalid plugins' error. how can i fix this. You know that it is normally used with <select.

and i would like to feature

(Install/Remove) button to manage plugins
![3](https://user-images.githubusercontent.com/36341134/131190518-54942c9b-0cb6-4246-ab5c-fd695eca90e4.PNG)

![1](https://user-images.githubusercontent.com/36341134/131189831-84a0c846-fcf1-4cb2-8422-8af80f9e1699.PNG)

ERROR:
![2](https://user-images.githubusercontent.com/36341134/131189834-aeadd9c0-1e02-45bb-a740-870bd765c99a.png)

[addons_installer.php.txt](https://github.com/OpenGamePanel/OGP-Website/files/7069483/addons_installer.php.txt)

**Comment by izmoxkawaii** [comment]
https://www.opengamepanel.org/forum/viewthread.php?thread_id=7753&highlight=plugin&pid=40222#post_40222

**Comment by Zorrototo** [comment]
You opened a feature request, then posted random error with random code with no explanation.

If you want support, open a support thread following the posting rules, and giving lot of information.

If you want a feature request post a proper feature request

If you mix everything and communicate like you're on tweeter, that's not gonna work.

**Comment by UmutLykia** [comment]
> Bir özellik isteği açtınız, ardından herhangi bir açıklama yapmadan rastgele kodla rastgele hata gönderdiniz.
> 
> Destek istiyorsanız, ilan kurallarına uyarak ve bolca bilgi vererek bir destek başlığı açın.
> 
> Bir özellik isteği istiyorsanız, uygun bir özellik isteği gönderin
> 
> Her şeyi karıştırır ve tweeter kullanıyormuş gibi iletişim kurarsanız, bu işe yaramaz.

You are not helping at all, my friend, I opened a topic in the forum, but no one was interested, I want you to help me here about this issue.

**Comment by UmutLykia** [comment]
I'm Turkish this panel was made for my company please help bro please help
