### ISSUE TITLE
server name to non English characters not possible anymore.

### ISSUE THREAD

**Issue by TAPL-93** [OpenGamePanel/OGP-Website#566]
Since the "Security Hardening" commit, it now not possible to set server name to non English characters.

http://prntscr.com/1qr69yd

**Comment by Zorrototo** [comment]
Reopening as if verified it is a legit Panel issue.

Can you write here characters that do not work?

**Comment by TAPL-93** [comment]
Nevermind, turned out to be an issue with the database encoding.

**Comment by Zorrototo** [comment]
OK then.
