### ISSUE TITLE
OGP-Website/modules/config_games/server_configs/wreckfest_win32.xml

### ISSUE THREAD

**Issue by ancientevil** [OpenGamePanel/OGP-Website#567]
Wreckfest moved their .exe file to serverroot and also now has a 64bits version of wreckfest.exe (Wreckfest_x64.exe )

Therefor configfile wont work anymore
//ancient

**Comment by Zorrototo** [comment]
Can you send a Pull Request with new modification, and a new 64 bit XML too?

**Comment by ancientevil** [comment]
Sure! Np

**Comment by Zorrototo** [comment]
I may have a look at it but I don't have a Windows server currently and don't know this server compatibility with WINE (it should work but that adds a point of failure to my tests if I do it, and could make me waste time).

**Comment by ancientevil** [comment]
Well i can help for the tryout on windows server

**Comment by ancientevil** [comment]
Perhaps easiest way to fix this is by changing

 <server_exec_name>server/Wreckfest.exe</server_exec_name> to
  <server_exec_name>Wreckfest.exe</server_exec_name>

**Comment by Zorrototo** [comment]
I didn't have time to look at it. If you can test and report that would help.

**Comment by ancientevil** [comment]
Yepp tried that and now win32 works again @Zorrototo

**Comment by Zorrototo** [comment]
Fixed https://github.com/OpenGamePanel/OGP-Website/commit/fa4c30fb9a43f46134246cf9b48d447a08f92555

I noticed a Wreckfest64.exe in the folder, I may also add an XML config to OGP for the 64bits version later. But for now the 32bits one is fixed.
