### ISSUE TITLE
Show API Actions popup encoding issue in Russian

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#571]
Seems like when you set your Panel to Russian language, there is an issue with character encoding in the popup listing the API actions. Couldn't find the culprit for now.

forum thread: https://www.opengamepanel.org/forum/viewthread.php?thread_id=7785

Initial commit for the API Actions: https://github.com/OpenGamePanel/OGP-Website/commit/45d7ee5593ba6b12f979c5c278c77f489cd51bda#diff-a8a7b534a9b07a66d27cf332e34ec51193df73b5bbb3ded1ca047e4fde125123

Maybe related to the javascript handling the whole thing /js/magnific/magnific.js or the related code there https://github.com/OpenGamePanel/OGP-Website/commit/fc984e7d2533c9f790c478c9330132e0ca311ac0#diff-57810548c4e738237dde119b243b0d868c4a56c8d4d9e58f4abb5b554a6ee4fc

**Comment by own3mall** [comment]
Should be fixed by:  https://github.com/OpenGamePanel/OGP-Website/pull/572
