### ISSUE TITLE
OGP-Website/modules/config_games/server_configs/squad_win64.xml SQUAD UPDATED TO 2.12

### ISSUE THREAD

**Issue by ancientevil** [OpenGamePanel/OGP-Website#574]
Squad updated to 2.12

I noticed that DEVS changed path for exe file to the following:

SquadGame/Binaries/Win64/SquadGameServer.exe

From the DEVS

So I'm aware of two things now:
- Some of you are using a launch script that references the SquadGameServer.exe in the main folder, which is no longer there, but should be referencing the SquadGameServer.exe file in SquadGame\Binaries\Win64. Changing it to the latter should be functional.

- - Linux servers seem to be having an issue where the /SquadGame/Saved/Config/LinuxServer folder including engine.ini isn't created, we're currently investigating this.

**Comment by ancientevil** [comment]
I hope that is the only change the made for file structure

**Comment by Zorrototo** [comment]
What's the second thing?

**Comment by ancientevil** [comment]
Oh sry added post above

**Comment by Zorrototo** [comment]
Can you try this change https://github.com/OpenGamePanel/OGP-Website/pull/575 (check the Files changed tab) to see if it works properly like that with this update that changes exe location?

**Comment by ancientevil** [comment]
Thank you! It works!

**Comment by Zorrototo** [comment]
Alright, I trust your feedback and merge it in OGP. I'll check Linux later.
