### ISSUE TITLE
Game server conflict with Windows and Linux version installed

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#577]
When you have a game server type installed, for example here Post Scriptum, with both Windows and Linux game servers of this same type installed, there is an issue occurring, for example the Game Monitor main page `/home.php?m=gamemanager&p=game_monitor` and the menu both list all existing game servers under the game server name category Post Scriptum, but if you click on Post Scriptum category in the menu then you only have the listing for one type of servers (Linux for example, all the other type are not listed) on the linked page `/home.php?m=gamemanager&p=game_monitor&home_cfg_id=169` (same thing using the dropdown category list in the game monitor page).

**Comment by own3mall** [comment]
Should be fixed now.

**Comment by Zorrototo** [comment]
https://github.com/OpenGamePanel/OGP-Website/pull/579
