### ISSUE TITLE
LiteFM Module Bugs

### ISSUE THREAD

**Issue by Adjokip** [OpenGamePanel/OGP-Website#58]
A couple of issues I came across in the LiteFM module:

1) Refreshing the page when viewing a file causes 'Failed to read file from the remote server.' to be printed.

This happens because on every page load within the filemanager, the `litefm_check` function is called. This function will select a value from the `fm_files_id` session array where the key is equal to that of `$_GET['item']`

It'll then append the value it gets to the `fm_cwd_id` session array, every page load. Thus, if you're viewing a file named LOG_HOME.txt and then refresh, your fm_cwd_id session variable becomes:
```
/LOG_HOME.txt
```

So it attempts to read: `/home/ogp_agent/OGP_User_Files/2/LOG_HOME.txt/LOG_HOME.txt` and will continue to append the file name as much as you refresh.

2) Opening large files can cause a Fatal Error depending on your memory_limit.

Well, that's with a 35MB file and the 128M default memory limit. This is not _just_ due to the size of the files. Files are sent by the agent and are encoded via base64, on the receiving side - the panel - the decoding uses most of that memory (90MB for the aforementioned file)

An idea may be to implement a size restriction on files that may be opened. To get the size information available to fm_read.php, fm_dir.php should also be edited, maybe to change the structure of the `fm_files_id` array as below:

```php
$_SESSION['fm_files_'.$home_id][$i] = [
	'name'	=>	$file['filename'],
	'size'	=>	$file['size'],
];
```

The same would need to be done for the directory and binary section. And anywhere referencing `fm_files_id` would need to be updated.

**Comment by own3mall** [comment]
Very low priority on this.  If you'd like, feel free to fix it for us.

**Comment by own3mall** [comment]
Closing this out as "won't fix" for now.  It's not a big deal, and for large files, you should be using FTP anyways.

Feel free to re-open or fix the above issues if you come up with a good way to do it, but I'm not doing it for the moment.

**Comment by rocco27** [comment]
Is this bug effect for changing path while you managing the files in LiteFM?

For example I unloack a file in a specific path, then I want to delete it, but the path changed automaticly somehow, so I have to navigate back manually to the prev. path where I unlocked the file.

**Comment by own3mall** [comment]
Should be fixed now.
