### ISSUE TITLE
counter-strike-linux, set cpu affinity and nice level not working

### ISSUE THREAD

**Issue by robijas** [OpenGamePanel/OGP-Website#595]
does someone else have this problem or is it just me?

adding cpu affinity or cpu nice level not working, im using debian 11 > apache2 > php 7.4

can anyone guide me into right direction what im doing wrong?

**Comment by Zorrototo** [comment]
First thing you're doing wrong is considering GitHub issue reporting a help forum. Go to the forum and open up a thread, following the support forum rules. Either you have an issue you have identified and can reproduce, give relevant information about it, or you don't. Don't report non issues you don't even know are issues.

**Comment by Zorrototo** [comment]
After investigating the Agent applies the settings as you can see in its log, to the approriate PIDs, but it doesn't result in working renicing. Probably related to the changes in Agent here https://github.com/OpenGamePanel/OGP-Agent-Linux/commit/14970749596efc05c6b8860b7b44652a492e70dc

**Comment by own3mall** [comment]
Should be fixed.

https://github.com/OpenGamePanel/OGP-Agent-Linux/commit/68649f2f77583e461f8545432e79abdad727e07a

Please retest, confirm, and close issue if fixed.

**Comment by Zorrototo** [comment]
It seems latest Agent changes fixed this renicing and CPU affinity issue.

@robijas can you update your Agent (basically restart it from Panel on default settings) and try again?

**Comment by robijas** [comment]
Yes it works again, i can confirm that the problem is solved now. TY
