### ISSUE TITLE
.atom not available anymore

### ISSUE THREAD

**Issue by DieFeM** [OpenGamePanel/OGP-Website#597]
Someone by the nick of [Sh4d0wless](https://github.com/Sh4d0wless) posted the following message in the wrong place, but it is an actual problem.
> Unable to download : https://github.com/OpenGamePanel/OGP-Website/commits/OGP-Website.atom
> Unable to update: String could not be parsed as XML

It seems that github disabled them (404), so we'd need to rewrite two modules, extras and update, in order to fetch the data that was being retrieved from .atom.

For example : [https://api.github.com/repos/OpenGamePanel/OGP-Website/commits](https://api.github.com/repos/OpenGamePanel/OGP-Website/commits)

[REST API - Commits @ docs.github.com](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28)

**Comment by Sh4d0wless** [comment]
![Screenshot_20230531-222304](https://github.com/OpenGamePanel/OGP-Website/assets/61610498/d755970c-ca9a-4218-a6cb-381affcfeb28)

**Comment by Sh4d0wless** [comment]
![Screenshot_20230531-222722](https://github.com/OpenGamePanel/OGP-Website/assets/61610498/2d74de69-e883-4d4e-9598-66cb5ed0c236)

**Comment by own3mall** [comment]
@Sh4d0wless, yes, I understand you are running into this problem, but no one knows why, and _it's just you_.

Please provide the panel setting value of `GitHub update username` found in `Administration` --> `Panel Settings`.  Also, this should not be set unless you are trying to update files from your branch, and if you're using a value here, it should only be your github username and nothing more.

**Comment by Sh4d0wless** [comment]
![Screenshot_20230531-224503](https://github.com/OpenGamePanel/OGP-Website/assets/61610498/43aa674f-b0f1-4005-a7e8-e92daf955650)

**Comment by own3mall** [comment]
@Sh4d0wless Yep, that's the problem.  You set GitHub branch name, which is wrong.  Clear both values for `GitHub update username` and `GitHub branch name`.  Unless you know what these settings do, you should not be setting or configuring them.

**Comment by Sh4d0wless** [comment]
you should remove that all , for not confuze users :) tnx, now works...

**Comment by own3mall** [comment]
Or you know, you could move your mouse over the "?" icon and read what it says...

![Screenshot at 2023-05-31 14-54-54](https://github.com/OpenGamePanel/OGP-Website/assets/11792538/6d8b3d97-8e88-4815-b15a-370690ed7808)

**Comment by Sh4d0wless** [comment]
looks like XP :) old but gold... tnx for everything...
