### ISSUE TITLE
symbols

### ISSUE THREAD

**Issue by Sh4d0wless** [OpenGamePanel/OGP-Website#609]
hello again
why i cannot use symbols in game/server name like this big red dot  🔴  --> https://www.gametracker.com/search/?query=wlg
when i add that symbol from **EDIT** -> **Game server name**: it does not changeing

**Comment by own3mall** [comment]
Set custom chars in the config file itself if you want a server name like that.

**Comment by Sh4d0wless** [comment]
> Set custom chars in the config file itself if you want a server name like that.

does not work... its changeing by its self in server.cfg

**Comment by Sh4d0wless** [comment]
i tryed make server.cfg - not redwriteble but anyway its changing

**Comment by Sh4d0wless** [comment]
start /normal  /wait C:\OGP64\home\cyg_server\OGP_User_Files\27020\hlds.exe -console -game cstrike -pidfile ogp_game_startup.pid +map zm_cave_new +ip 80.241.245.222 +port 27020 +maxplayers 32 -condebug +hostname \"• 🔴     WLG Zombie     🔴 •\" -bots

anyway server name will be "WLG Zombie"

**Comment by own3mall** [comment]
Change the xml config file for the game to not replace it from the name in the panel.

**Comment by Zorrototo** [comment]
https://github.com/OpenGamePanel/OGP-Website/wiki/XML-Notes#cli-allowed-characters ?
