### ISSUE TITLE
Game Panel Game Server name

### ISSUE THREAD

**Issue by Mustafa982** [OpenGamePanel/OGP-Website#610]
Hello, i have problem when i put arabic game server name arabic or other language it showing like this : https://imgur.com/a/iUDpbU6 its doing ??? i have many customer in my host company and everyone coming from other country and many of them are from Arabs so we have this problem, i have another much more problems but i gonna do a new topic in that hope you find a solution in that thanks for reply me :) :D

**Comment by Zorrototo** [comment]
It seems to work for me:

![Screenshot_20230723_151339](https://github.com/OpenGamePanel/OGP-Website/assets/17416415/74210999-7204-4f4f-ad1a-753c166ff74a)

I did not try with a fresh OS/OGP installation, mine is fairly old, but from what I see it just works.

Did you install OGP manually with your own DB and web server, or did you use the Easy Installer on a fresh OS installation?

Maybe your database is not on proper settings, maybe it is your Panel files that are modified, maybe something else. Hard to say.

**Comment by Mustafa982** [comment]
i have been also changed the thems still have same issues and my version in ogp panel is Panel version: 7270d0e86ea01da4069d905648b522c252fdca45

Latest version: 7270d0e86ea01da4069d905648b522c252fdca45

**Comment by Zorrototo** [comment]
I can't force you to give information. Back to the forum as it is not an OGP bug but problem seems to be on your side.

**Comment by Mustafa982** [comment]
i have been installed fresh OS/OGP installation easy steps rocky linux 9 and i did all these instructions and everything worked as well but change server name to arabic does not works.

**Comment by Zorrototo** [comment]
OK. I reopen on behalf of what you said then. In the meantime can you try with another web browser, your phone, other browsers basically. I will do a fresh install later this week, no guarantee on when I will be able to.

**Comment by Mustafa982** [comment]
okay, please reply when you try install a fresh ogp panel :) thanks so much for helping

**Comment by own3mall** [comment]
Can you paste the exact Arabic name you're using for the game server?

**Comment by Mustafa982** [comment]
{H.K} {هاكرز العرب للزومبي} {H.K}

**Comment by own3mall** [comment]
It worked fine for me.  It could be a theme issue.

![image](https://github.com/OpenGamePanel/OGP-Website/assets/11792538/6c10783e-fb5e-4148-8f6b-312027a54bd9)

**Comment by Mustafa982** [comment]
no sir i have been also changed the thems...

**Comment by Mustafa982** [comment]
https://imgur.com/a/yP7iZIU
