### ISSUE TITLE
disable access for users to see addonmanager/list content

### ISSUE THREAD

**Issue by Amine-Aziz** [OpenGamePanel/OGP-Website#623]
Sometimes, as a Game Hosting provider using OpenGamePanel you add some addons that require Sudo password, MySQL root passwords, etc... adding it to the AddonManager will be dangerous because users can see the Bash script content from test_api.php file by using OGP API Key so they can get an important password, **My solution is** Remove the addon addonmanager/list option from ogp_api.php file or just remove the ogp_api.php file

**Comment by Zorrototo** [comment]
You can also maybe find a way to not use sudo password in plain text in your addons maybe? like adding specific exact commands or just an executable rights to be executed without sudo password. All that would be done in /etc/sudoers

I agree that maybe listing the addons script could be removed too, to not leak other things like private URLs, or whatever you don't want to share with the world. Maybe some restriction on the API could be added to to retrict ome thing to an Admin (I don't use the API and didn't look how it currently works yet).

**Comment by own3mall** [comment]
Fixed.  Contents of the script are no longer returned in the API list lookup.
