### ISSUE TITLE
_page_limit_ user setting does not save

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#85]
As title says, _page_limit_ user setting does not save at all for me. Database contains the new users->users_page_limit so update went well, but nothing saves to the DB.

**Comment by own3mall** [comment]
Mine saves... What value are you using?  It can't be less than 10 or else it gets set to the default of 25.

**Comment by Zorrototo** [comment]
OK that's it, I used 5 as a value to test.

**Comment by own3mall** [comment]
Done.  Needs https://github.com/OpenGamePanel/OGP-Website/commit/33c42df5f6ec3a65e8f6c4f18ee79760cc3f6940#diff-1cea580b88533a31aede6c14de47b4d5 added to other languages via Transifex.
